BHoM/Revit_Toolkit

- Engine_Revit_UI/Compute/Notes.cs
- Engine_Revit_UI/Compute/Warnings.cs
- Engine_Revit_UI/Convert/Common/ToBHoM/Material.cs
- Engine_Revit_UI/Convert/Structure/ToBHoM/SectionProperty.cs
- Engine_Revit_UI/Engine_Revit_UI.csproj
- Engine_Revit_UI/Query/LibraryMaterial.cs
- Engine_Revit_UI/Query/MaterialType.cs
- Engine_Revit_UI/Query/StructuralMaterialType.cs
> Revit_Toolkit - Issue 206 - Default Materials

- Adapter_Revit_UI/Read/Read.cs
- Engine_Revit_UI/Compute/Warnings.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/BuildingElement.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/BuildingElementProperties.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/MaterialPropertiesOpaque.cs
- Engine_Revit_UI/Convert/ToBHoM.cs
- Engine_Revit_UI/Engine_Revit_UI.csproj
- Engine_Revit_UI/Query/BHoMTypes.cs
- Engine_Revit_UI/Query/Construction.cs
- Engine_Revit_UI/Query/Element.cs
- Engine_Revit_UI/Query/ElementId.cs
- Engine_Revit_UI/Query/EnergyAnalysisElementName.cs
- Engine_Revit_UI/Query/FamilyTypeFullName.cs
- Engine_Revit_UI/Query/GetEnergyAnalysisModel.cs
- Engine_Revit_UI/Query/Material.cs
- Revit_Engine/Query/PullEdges.cs
Closes #210 
Closes #192 
Closes #208 
Closes #212
> Revit_Toolkit - Issue 210 - Combined FamilyName and FamilyTypeName

- Engine_Revit_UI/Convert/Environment/ToBHoM/Building.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/BuildingElement.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/Opening.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/Space.cs
- Engine_Revit_UI/Engine_Revit_UI.csproj
- Engine_Revit_UI/Modify/SetCustomData.cs
- Engine_Revit_UI/Query/GetEnergyAnalysisModel.cs
- Engine_Revit_UI/Query/Name.cs
Implementation of ExtendedProperties
Moving Opening code to separate unit (ToBHoMOpening method)
Closes #237 
Dependent on:
https://github.com/BHoM/BHoM_Engine/pull/830
> Revit_Toolkit - Issue237 - New Environment Framework

- Engine_Revit_UI/Convert/Environment/ToBHoM/Opening.cs
- Engine_Revit_UI/Modify/AppendRefObjects.cs
Pull opening issue fixed
Closes #248
> Revit_Toolkit - Issue 248 - Pull Opening Issue

- Adapter_Revit_UI/Delete/Delete.cs
- Engine_Revit_UI/Compute/Warnings.cs
- Engine_Revit_UI/Convert/Common/ToRevit/Material.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/Building.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/Opening.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/Panel.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/SolidMaterial.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/Space.cs
- Engine_Revit_UI/Convert/Environment/ToRevit/CompoundStructure.cs
- Engine_Revit_UI/Convert/Environment/ToRevit/CompoundStructureLayer.cs
- Engine_Revit_UI/Convert/Environment/ToRevit/ElementType.cs
- Engine_Revit_UI/Convert/ToRevit.cs
- Engine_Revit_UI/Query/BHoMTypes.cs
- Engine_Revit_UI/Query/Construction.cs
- Engine_Revit_UI/Query/GetEnergyAnalysisModel.cs
- Engine_Revit_UI/Query/Layer.cs
- Revit_Engine/Create/Elements/Panel.cs
- Revit_Engine/Modify/SetFamilyName.cs
- Revit_Engine/Modify/SetFamilyTypeName.cs
- Revit_Engine/Query/DefaultMapSettings.cs
https://github.com/BHoM/BHoM/pull/479
https://github.com/BHoM/BHoM_Engine/pull/938
Fixes #181  
N/A
- Changed to reflect changes to oMs.
> Revit_Toolkit: Align to oM changes

- Engine_Revit_UI/Convert/Environment/ToBHoM/Opening.cs
Fixes #288 
[Test File](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue288-GetInstanceTypeOpeningParameters?csf=1&e=KPJB9s)
- Fix Openings Type Parameters
> Fix Openings Type Parameters

- Adapter_Revit_UI/Types/Comparer.cs
- Engine_Revit_UI/Compute/Notes.cs
- Engine_Revit_UI/Compute/Warnings.cs
- Engine_Revit_UI/Convert/Revit/ToBHoM/Material.cs
- Engine_Revit_UI/Convert/Revit/ToBHoM/Object2DProperties.cs
- Engine_Revit_UI/Convert/Structure/ToBHoM/FramingElement.cs
- Engine_Revit_UI/Convert/Structure/ToBHoM/PanelPlanar.cs
- Engine_Revit_UI/Convert/Structure/ToBHoM/Profile.cs
- Engine_Revit_UI/Convert/Structure/ToBHoM/SectionProperty.cs
- Engine_Revit_UI/Convert/Structure/ToBHoM/SurfaceProperty.cs
- Engine_Revit_UI/Convert/Structure/ToRevit/FamilyInstance.cs
- Engine_Revit_UI/Convert/Structure/ToRevit/FamilySymbol.cs
- Engine_Revit_UI/Convert/Structure/ToRevit/Floor.cs
- Engine_Revit_UI/Convert/Structure/ToRevit/FloorType.cs
- Engine_Revit_UI/Convert/Structure/ToRevit/HostObject.cs
- Engine_Revit_UI/Convert/Structure/ToRevit/Wall.cs
- Engine_Revit_UI/Convert/Structure/ToRevit/WallType.cs
- Engine_Revit_UI/Convert/ToRevit.cs
- Engine_Revit_UI/Query/BHoMTypes.cs
- Engine_Revit_UI/Query/CompoundLayer.cs
- Engine_Revit_UI/Query/CompoundLayers.cs
- Engine_Revit_UI/Query/LibraryMaterial.cs
- Engine_Revit_UI/Query/RevitTypes.cs
- Revit_Engine/Query/DefaultMapSettings.cs
https://github.com/BHoM/BHoM/pull/481
https://github.com/BHoM/BHoM_Engine/pull/951
Closes #280 
Revit toolkit updated due to changes in the Structure oM and Engine
Please test through as many project scripts etc as possible to make sure things are working as intended
> Revit toolkit issue280 update to changes in b ho m

- Engine_Revit_UI/Convert/Environment/ToBHoM/SolidMaterial.cs
- Engine_Revit_UI/Query/Construction.cs
https://github.com/BHoM/BHoM/pull/490
https://github.com/BHoM/BHoM_Engine/pull/976
Fixes #295  
Existing test scripts
- Changed material access properties to reflect changes in oM and engine
Part of a wider merge, please do not merge without clearance! :smile:
I have checked, this should have no rebase conflicts with the previous PR opened by @pawelbaran as this does not change the same files :smile:
> Revit_Toolkit: Update to material oM change

- Engine_Revit_UI/Convert/Architecture/ToRevit/Level.cs
Push Levels units fixed
Closes #290 
[Test Dynamo Script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue290-PushingLevels?csf=1&e=P8nvMX)
> Revit_Toolkit-Issue290-PushingLevels

- Engine_Revit_UI/Convert/Environment/ToBHoM/Space.cs
- Engine_Revit_UI/Query/Name.cs
Space Name updated to match Environmental standards
Closes #273 
[Sample Script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue273-SpaceName?csf=1&e=2zL8kZ)
> Revit_Toolkit-Issue273-SpaceName

- Revit_Engine/Query/FamilyTypeFullName.cs
Full Name updated to match with Revit convention.
Old Full Name:
[FamilyName] : [FamilyTypeName]
New Full Name
[FamilyName]: [FamilyTypeName]
Closes #279
To be provided by disciplines
>  Revit_Toolkit-Issue279-FamilyTypeFullName

- Engine_Revit_UI/Convert/Environment/ToBHoM/Panel.cs
- Revit_Engine/Create/Elements/Panel.cs
https://github.com/BHoM/BHoM/pull/508
https://github.com/BHoM/BHoM_Engine/pull/1036
Fixes #320 
N/A
- Changed fragment namespace in line with BHoM changes
Do not merge until BHoM PR is ready
Will not conflict with existing PR on Addins.
> Revit_Toolkit: Update to fragments

- Engine_Revit_UI/Convert/FromSI.cs
- Engine_Revit_UI/Convert/ToSI.cs
N/A
Closes #310 
Pull/Push Macro test and check units for Custom Data
- Airflow unit added
- Heating Load unit added
- Cooling Load unit added
N/A
> Revit_Toolit - Issue 310 - Add Missing Unit Types

- Engine_Revit_UI/Compute/LoadFamily.cs
- Engine_Revit_UI/Compute/LoadFamilySymbol.cs
- Engine_Revit_UI/Engine_Revit_UI.csproj
- Revit_Engine/Revit_Engine.csproj
N/A
Closes #302 
No test file needed. Run any pull/push script
- LoadFamilySymbol moved from Modify to Compute
- LoadFamily moved from Modify to Compute
N/A
> Revit_Toolkit - Issue 302 - Reorganise Compute and Modify Methods

- Engine_Revit_UI/Convert/Environment/ToBHoM/Space.cs
N/A
Closes #307
Location of Space assigned
[Test Scripts](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue307-SpaceLocation?csf=1&e=HWK9lL)
ToBHoMSpace method updated
N/A
> Revit_Toolkit - Issue 307 - Space Location

- Adapter_Revit_UI/Adapter_Revit_UI.csproj
- Revit_Adapter/RevitAdapter.cs
#340 
Closes #340 
Descriptions added to RevitAdapter
N/A
> Added descriptions to Revit adapter as per issue #340

- .github/ISSUE_TEMPLATE/api_changed.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/compliance.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/test_script.md
N/A
Closes #345 
Templates added
N/A
Templates added
N/A
> Revit_Toolkit - #345 - Issue Templates

- Adapter_Revit_UI/Properties/AssemblyInfo.cs
- Engine_Revit_UI/Properties/AssemblyInfo.cs
- Revit_Adapter/Properties/AssemblyInfo.cs
- Revit_Engine/_Properties/AssemblyInfo.cs
- Revit_Test/Properties/AssemblyInfo.cs
- Revit_UI/Properties/AssemblyInfo.cs
- Revit_oM/_Properties/AssemblyInfo.cs
Fixes #344
N/A
- Changed Assembly file version
> Revit_Toolkit: Assembly info update

- Engine_Revit_UI/Convert/Architecture/ToBHoM/Room.cs
- Engine_Revit_UI/Convert/ToBHoM.cs
- Engine_Revit_UI/Engine_Revit_UI.csproj
- Engine_Revit_UI/Query/BHoMTypes.cs
- Engine_Revit_UI/Query/BuiltInCategories.cs
- Engine_Revit_UI/Query/Profiles.cs
- Engine_Revit_UI/Query/RevitTypes.cs
https://github.com/BHoM/BHoM/pull/539
Fixes #359 
I'm not sure if this is working because I actually did not have any models suitable for this. I am marking this as WIP to be safe.
@ZiolkowskiJakub please review - and if it doesn't work please can you fix in my absence?
@kayleighhoude FYI :smile:
> Pull rooms

- Engine_Revit_UI/Convert/Geometry/ToBHoM/Grid.cs
- Engine_Revit_UI/Convert/Geometry/ToBHoM/Level.cs
- Engine_Revit_UI/Convert/Geometry/ToRevit/Grid.cs
- Engine_Revit_UI/Convert/Geometry/ToRevit/Level.cs
- Engine_Revit_UI/Convert/ToRevit.cs
- Engine_Revit_UI/Engine_Revit_UI.csproj
- Engine_Revit_UI/Query/BHoMTypes.cs
- Engine_Revit_UI/Query/RevitTypes.cs
https://github.com/BHoM/BHoM/pull/554
https://github.com/BHoM/BHoM_Engine/pull/1204
Closes #369 
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FArchitecture%5FoM%2F%23536%20%2D%20migration%20of%20grid%20and%20level&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4
- `Convert.ToBHoMGrid(this Grid grid, PullSettings pullSettings = null)` method moved to Geometry (SettingOut)
- `Convert.ToBHoMLevel(this Level level, PullSettings pullSettings = null)` method moved to Geometry (SettingOut)
- `Query.RevitTypes([...])` references updated
- `Query.Level()` references updated
- `Query.BHoMTypes([...])` references updated
- `Convert.ToRevit([...])` references updated
> Update Grids & Levels from Architecture to Geometry.SettingOut

- Engine_Revit_UI/Query/BuiltInCategories.cs
- Engine_Revit_UI/Query/RevitTypes.cs
N/A
Closes #382  
[Pull ISurface Test](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue382-PullSurface?csf=1&e=Ok4SGN)
- 'BuiltInCategories' method updated to include BH.oM.Physical.Elements.ISurface
- 'RevitTypes' method updated to include BH.oM.Physical.Elements.ISurface
N/A
> Pull ISurface Implementation

- Adapter_Revit_UI/Create/Create.cs
Closes #399
Test file uploaded to [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue399%2DPreventFromAttemptToPushAnalyticalPanels) - can be run on any model.
- attempt to push analytical panels has been disabled
> Prevent from attempt to push analytical panels

- Adapter_Revit_UI/Create/Create.cs
- Engine_Revit_UI/Convert/Environment/ToRevit/Space.cs
- Engine_Revit_UI/Convert/ToRevit.cs
- Engine_Revit_UI/Engine_Revit_UI.csproj
- Engine_Revit_UI/Modify/Move.cs
- Engine_Revit_UI/Query/BottomLevel.cs
N/A
Closes #374
[Push Space Dynamo script and Revit Model](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue374-PushSpace?csf=1&e=vmp2Zw)
- 'ToRevitSpace' method implemented
- 'ToRevit' method for Enviromental Space added 
N/A
> Implement push of Environment.Space to Revit

- Engine_Revit_UI/Compute/Warnings.cs
- Engine_Revit_UI/Convert/Revit/ToRevit/Element.cs
Closes #308 
Test file is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue308%2DAddPosibilityToPlaceModelInstanceTwoLevelBased).
Allowed creation of a two-level based family instance with location defined by a curve.
> Add posibility to place modelInstance Two-levelbased

- Adapter_Revit_UI/Properties/AssemblyInfo.cs
- Engine_Revit_UI/Properties/AssemblyInfo.cs
- Revit_Adapter/Properties/AssemblyInfo.cs
- Revit_Engine/_Properties/AssemblyInfo.cs
- Revit_UI/Properties/AssemblyInfo.cs
- Revit_oM/_Properties/AssemblyInfo.cs
N/A
Closes #411
N/A
- `AssemblyInfo.cs` files updated with the latest version for all the projects
N/A
> AssemblyInfo Updated

- Engine_Revit_UI/Convert/Environment/ToBHoM/Building.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/Space.cs
- Engine_Revit_UI/Engine_Revit_UI.csproj
N/A
Fixes #419 
Fixes #418 
Run standard Pull Revit push gbXML file
* Fix fragments
* remove unused reference
N/A
> Building Pull Bug

- Engine_Revit_UI/Convert/Environment/ToBHoM/Space.cs
Fixes #423 
[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue423-PullSpaces?csf=1&e=4n2MgL)
* fix fragments to pull space
> Fix Pull Space

- Engine_Revit_UI/Convert/Physical/ToBHoM/ISurface.cs
> Fix Physical roof creation

- Engine_Revit_UI/Convert/Architecture/ToRevit/Ceiling.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/Building.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/Panel.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/SolidMaterial.cs
- Engine_Revit_UI/Convert/Environment/ToBHoM/Space.cs
- Engine_Revit_UI/Convert/Environment/ToRevit/Element.cs
- Engine_Revit_UI/Convert/Environment/ToRevit/Space.cs
- Engine_Revit_UI/Convert/FromSI.cs
- Engine_Revit_UI/Convert/Geometry/ToBHoM/ICurve.cs
- Engine_Revit_UI/Convert/Geometry/ToBHoM/Point.cs
- Engine_Revit_UI/Convert/Geometry/ToBHoM/Vector.cs
- Engine_Revit_UI/Convert/Geometry/ToRevit/Curve.cs
- Engine_Revit_UI/Convert/Geometry/ToRevit/Vector.cs
- Engine_Revit_UI/Convert/Geometry/ToRevit/XYZ.cs
- Engine_Revit_UI/Convert/Physical/ToRevit/Floor.cs
- Engine_Revit_UI/Convert/Physical/ToRevit/RoofBase.cs
- Engine_Revit_UI/Convert/Physical/ToRevit/Wall.cs
- Engine_Revit_UI/Convert/Structure/ToBHoM/MaterialFragment.cs
- Engine_Revit_UI/Convert/ToSI.cs
- Engine_Revit_UI/Engine_Revit_UI.csproj
- Engine_Revit_UI/Query/BHoMUnitType.cs
- Engine_Revit_UI/Query/BottomLevel.cs
- Engine_Revit_UI/Query/BuiltInCategories.cs
- Engine_Revit_UI/Query/GetEnergyAnalysisModel.cs
- Engine_Revit_UI/Query/HighLevel.cs
- Engine_Revit_UI/Query/Layer.cs
- Engine_Revit_UI/Query/LowElevation.cs
- Engine_Revit_UI/Query/LowLevel.cs
- Engine_Revit_UI/Query/Profiles.cs
Closes #465 
Standard macro test files available on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro). However, careful reading should be enough in this case.
- `BH.UI.Revit.Engine.Query.BHoMUnitType(UnitType)` has been added
- BHoM <-> Revit unit conversion has been unified
> Unified Unit Conversion

- Adapter_Revit_UI/Properties/AssemblyInfo.cs
- Engine_Revit_UI/Properties/AssemblyInfo.cs
- Revit_Adapter/Properties/AssemblyInfo.cs
- Revit_Engine/_Properties/AssemblyInfo.cs
- Revit_UI/Properties/AssemblyInfo.cs
- Revit_oM/_Properties/AssemblyInfo.cs
> AssemblyInfo Files Updated

- Engine_Revit_UI/Convert/Physical/ToRevit/FamilyInstance.cs
Closes #473 
Existing [macro script](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPush%2FPhysical)
> Pushing nurbs-based FramingElements reenabled

- Adapter_Revit_UI/Properties/AssemblyInfo.cs
- Engine_Revit_UI/Properties/AssemblyInfo.cs
- Revit_Adapter/Properties/AssemblyInfo.cs
- Revit_Engine/_Properties/AssemblyInfo.cs
- Revit_UI/Properties/AssemblyInfo.cs
- Revit_oM/_Properties/AssemblyInfo.cs
> AssemblyFileVersion changed to 3.1.0.0

- Engine_Revit_UI/Query/BHoMUnitType.cs
Closes #500
Added case for `UnitType.UT_Reinforcement_Spacing` to `DisplayUnitType BHoMUnitType`.
> Adding UT_Reinforcement_Spacing case

- Engine_Revit_UI/Convert/Physical/ToBHoM/FramingElement.cs
- Engine_Revit_UI/Convert/Physical/ToRevit/FamilyInstance.cs
Closes #495
Macro tests on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPull%2FStructure).
> Deprecated method call to IsVertical replaced with latest one

- Engine_Revit_UI/Convert/Revit/ToRevit/Element.cs
Closes #502 
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue502%2DEnablePushingMEPElementsAsModelInstances) - start a new Revit project with MEP template.
- Enabled pushing curve-based MEP elements as ModelInstances
It is a temp solution, in long term (once MEP_oM becomes mature enough) this should be expanded and better structured.
> Pushing MEP elements enabled

- Engine_Revit_UI/Convert/Geometry/ToRevit/CurveLoop.cs
- Engine_Revit_UI/Convert/Revit/ToBHoM/DraftingInstance.cs
- Engine_Revit_UI/Convert/Revit/ToRevit/Element.cs
- Engine_Revit_UI/Convert/ToBHoM.cs
- Engine_Revit_UI/Convert/ToRevit.cs
- Engine_Revit_UI/Engine_Revit_UI.csproj
- Engine_Revit_UI/Query/BHoMTypes.cs
- Revit_Engine/Create/Elements/DraftingInstance.cs
- [Geometry_Engine #1429](https://github.com/BHoM/BHoM_Engine/pull/1429)
Closes #505
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue505%2DSupportForFilledRegionsAndLineBasedDetailItems) - all is set up on _LEVEL 00 - GA_ view, as a minimum I would recommend pushing everything prepared in the GH script and then pulling all objects of type `DraftingInstance` (also prepared in the script).
- Push/pull of Filled Regions and line based Detail Items has been enabled.
Some macro test pulling a hatch-based load plan would be great - @IsakNaslundBh @kThorsager anything comes to your mind?
> Push/pull of line-based draftingInstances and filled regions enabled

- Engine_Revit_UI/Convert/Structure/ToBHoM/Bar.cs
- Engine_Revit_UI/Convert/Structure/ToBHoM/MaterialFragment.cs
- Engine_Revit_UI/Modify/UpdateMaterialProperties.cs
Closes #498
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue498%2DMaterialSupport).
Although there is no overlap, I would still recommend not clicking _Merge_ on this one before #520 gets merged.
> Support for Timber, Aluminium and Generic sections added

- Engine_Revit_UI/Convert/Architecture/ToBHoM/Room.cs
Fixes #540 
Existing and code review
> Remove duplicated code calling

- Engine_Revit_UI/Convert/Environment/ToBHoM/Building.cs
- Engine_Revit_UI/Convert/ToBHoM.cs
Fixes #537 
Existing and code review
> Change method name for compliance

- Adapter_Revit_UI/Adapter_Revit_UI.csproj
- Engine_Revit_UI/Engine_Revit_UI.csproj
- Revit_Engine/Revit_Engine.csproj
- Revit_oM/Revit_oM.csproj
https://github.com/BHoM/BHoM/pull/704
https://github.com/BHoM/BHoM_Engine/pull/1484
https://github.com/BHoM/BHoM_Adapter/pull/193
Closes #547 
Adds references to Dimensional_oM where necessary and 'using' statments where that is necessary 
to comply with the changes in https://github.com/BHoM/BHoM/pull/704
> Update IElement references with the Dimensional_oM

- Revit_Engine/Create/Elements/BHoMObject.cs
- Revit_Engine/Create/Elements/ModelInstance.cs
- Revit_Engine/Create/Elements/Panel.cs
- Revit_Engine/Create/Generic/TypeMap.cs
- Revit_Engine/Modify/AddMap.cs
- Revit_Engine/Modify/SetFamilyName.cs
- Revit_Engine/Modify/SetFamilyTypeName.cs
- Revit_Engine/Query/Family.cs
- Revit_Engine/Query/IsTemplate.cs
This PR resolved Revit_Engine side compliance issues. Engine_Revit_UI is meant to be resolved in a separate PR.
Test file on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue573%2DComplianceIssues) showing that the name argument name change gets picked up by the Versioning. All other changes should not require a test file.
Some descriptions that are touched in this PR are not too informative - they are legacy and need to be revisited each after each, which is beyond the scope of this PR, to be done in the coming weeks/months.
> Revit_Engine side compliance issues

- Engine_Revit_UI/Convert/Revit/ToBHoM/DraftingInstance.cs
- Engine_Revit_UI/Convert/Revit/ToRevit/Element.cs
- Revit_Engine/Create/Elements/DraftingInstance.cs
Closes #591
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue591%2DDisjointFilledRegions) - to be tested with view _LEVEL 00 - GA_
> Support for disjoint FilledRegions added

- Engine_Revit_UI/Modify/UpdateMaterialProperties.cs
- Engine_Revit_UI/Query/EnergyAnalysisElementName.cs
- Engine_Revit_UI/Query/HighElevation.cs
- Engine_Revit_UI/Query/HighLevel.cs
- Engine_Revit_UI/Query/HostedBuildingElements.cs
- Engine_Revit_UI/Query/IsVerticalNonLinearCurve.cs
- Engine_Revit_UI/Query/LowElevation.cs
- Engine_Revit_UI/Query/LowLevel.cs
- Engine_Revit_UI/Query/Name.cs
- Engine_Revit_UI/Query/PolyCurves.cs
- Revit_Engine/Query/FamilyTypeFullName.cs
Closes #538
Minor cosmetics, no change in mechanics so tests not needed.
> Public static methods turned into extension methods

- Revit_oM/Generic/TypeMap.cs
> virtual keyword and {get; set;} added to BH.oM.Adapters.Revit.Generic.Map

- Adapter_Revit_UI/AdapterActions/Push.cs
Closes #629
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue629%2DCreateNonExisting), follow the steps to test:
1. Open an empty Revit doc with BH structural template
2. Trigger first push from script
3. Delete some columns from Revit doc
4. Trigger second push from script
5. Inspect the Revit doc
> CreateNonExsiting enabled

- Engine_Revit_UI/Convert/Environment/FromRevit/Building.cs
- Engine_Revit_UI/Convert/Environment/FromRevit/Panel.cs
- Engine_Revit_UI/Convert/Environment/FromRevit/Space.cs
- Engine_Revit_UI/Convert/Structure/FromRevit/MaterialFragment.cs
- Engine_Revit_UI/Query/WorksetId.cs
Closes #670
[BEnv macro pull script](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPull%2FEnvironment%2FFrom%20MajaLindroth) is possibly the best way to test, project scripts are also welcome.
- discipline-related information stopped from being copied overt to object's `CustomData` on convert
- `BH.UI.Revit.Engine.Query.WorksetId` method has been deleted as a follow up to #664
> CustomData handling cleanup vol. 2

- Engine_Revit_UI/Query/IsContaining.cs
- Engine_Revit_UI/Query/PolyCurve.cs
Closes #682 
Updated old deprecated methods to their new equivalent methods
Can't say I'm sure on what these changes imply testing wise, but nothing should have changed
> Removing Deprecated Geometry methods

- Revit_Engine/Revit_Engine.csproj
> Data_oM reference set to copy local = false

- Engine_Revit_UI/Convert/Environment/FromRevit/Space.cs
Fixes #386 
Usual existing macro tests and code review
Have also removed dependency on deprecated code for creating space objects.
> Set space location to boundary centroid

- Engine_Revit_UI/Convert/Architecture/FromRevit/Ceilings.cs
- Engine_Revit_UI/Engine_Revit_UI.csproj
- Engine_Revit_UI/Query/CeilingPattern.cs
- Revit_Engine/Convert/Aliases.cs
Fixes #427
[Here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/%23688%20testing?csf=1&web=1&e=pzL9NY) (Ceiling.rvt kindly provided by @pawelbaran :smile: )
FYI: @TheresaBrown
Ceiling Pattern currently gets pulled through as custom data as there is no object suitable for it. This should be sufficient for current workflows.
> Pulling ceiling patterns

- Engine_Revit_UI/Convert/Geometry/FromRevit/Surface.cs
- Engine_Revit_UI/Query/PlanarSurfaceDictionary.cs
https://github.com/BHoM/BHoM/pull/861
https://github.com/BHoM/BHoM_Engine/pull/1761
Required as part of other PRs
Updates to use the new constructor, which does the same thing.
Should not be needed as no functional change is made.
Otherwise any macros which make use of these methods @pawelbaran ?
> Update following changes in the oM for PlanarSurface

- Engine_Revit_UI/Create/Workset.cs
- Engine_Revit_UI/Engine_Revit_UI.csproj
- Engine_Revit_UI/Modify/SetParameter.cs
- Engine_Revit_UI/Query/Workset.cs
Closes #663
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue663%2DWorkset%5Fchange&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
> Update of worksets enabled

- Engine_Revit_UI/Convert/Environment/FromRevit/Space.cs
Fixes #732 
Existing Environment scripts
@MajaLindroth to confirm functionality, @pawelbaran to confirm happy with code :smile:
> Add space perimeter to space pull

- Engine_Revit_UI/Convert/Environment/FromRevit/Space.cs
Closes #734 
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue734%2DUnboundedRoomBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
> Unbounded room stopped from crashing

- Engine_Revit_UI/Engine_Revit_UI.csproj
- Engine_Revit_UI/Query/ElementIds/ElementIds.cs
- Engine_Revit_UI/Query/ElementIds/ElementIdsByExclusion.cs
- Revit_Engine/Query/Discipline.cs
https://github.com/BHoM/BHoM/pull/890
https://github.com/BHoM/BHoM_Engine/pull/1798
Closes #730
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue730%2DLogicalNotRequest&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
There might be a minor conflict between this PR and #726 - happy to resolve it manually, first merge first serve.
> Handling of LogicalNotRequest implemented

- Revit_Adapter/Revit_Adapter.csproj
- Revit_Core_Adapter/Listener/Files/BHoM_2018.Addin
- Revit_Core_Adapter/Listener/Files/BHoM_2019.Addin
- Revit_Core_Adapter/Listener/Files/BHoM_2020.Addin
- Revit_Core_Adapter/Revit_Core_Adapter.csproj
- Revit_Core_Engine/Revit_Core_Engine.csproj
- Revit_Engine/Revit_Engine.csproj
- Revit_oM/Revit_oM.csproj
https://github.com/BHoM/admin/issues/5
Closes #743
> References and postbuilds updated to support the migration from Appdata to ProgramData

- Revit_Core_Engine/Convert/Environment/FromRevit/Opening.cs
- Revit_Core_Engine/Convert/Environment/FromRevit/Panel.cs
- Revit_Core_Engine/Convert/Environment/FromRevit/Space.cs
Fixes #738 
Fixes #736 
See issues
> Null protection on elements and data duplication fix

- Revit_Core_Engine/Query/LocationCurve.cs
Closes #761
Try pulling any nurbs-based element from FramingGeometry file on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2fsites%2fBHoM%2fInstallers%2fScripts%2fBuroHappold%5fBHoM%5fv3%2e2%2f0001%5fRevit%5fToolkit%2fPull&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302).
> Pull of nurbs-based framing fixed

- Revit_Core_Engine/Convert/Physical/ToRevit/FamilyInstance.cs
- Revit_Core_Engine/Modify/CopyParameters.cs
Closes #767
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue767%2DPushColumnOffsetBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
> Zero length column error on push eliminated

- Revit_Engine/Query/DefaultParameterSettings.cs
> Backslashes changed to slashes in descriptions

- Revit_Core_Engine/Convert/Environment/FromRevit/Panel.cs
Closes #800
- standard BEnv pull on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPull%2FEnvironment%2FFrom%20MajaLindroth&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- [general script to pull panels](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue800%2DConvertPanelsMEP&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4), could be tried with other models
- methods to query panel and opening outlines in BEnv panel converts from Revit replaced with `PanelSurfaces` and …
> PanelSurfaces and OpeningSurface methods introduced to BEnv panel converts from Revit

- Revit_Core_Engine/Query/Outlines.cs
Closes #821
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue821%2DAnalyticalPullIgnoresManualAdjustments&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
> Pull of analytical structural panels fixed to take manual adjustments into account

- Revit_Core_Engine/Convert/Structure/FromRevit/Panels.cs
https://github.com/BHoM/BHoM/pull/974
https://github.com/BHoM/BHoM_Engine/pull/1942
Aligning with changes to Structure_Engine
> Aligning with changes to panel creates

- Revit_Core_Engine/Convert/Structure/FromRevit/Profile.cs
Closes #835 
Closes #836
- [#835](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue835%2DUpsideDownProfiles&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- [#836](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue836%2DInactiveProfileCrash&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - it is important not to create an element of a given type before pulling (it gets activated on the first use)
- macro test - _PullFramingLocation_ from …
> Revit => BHoM freeform profile convert bugs fixed

- Revit_Core_Engine/Convert/Environment/FromRevit/Duct.cs
- Revit_Core_Engine/Convert/Environment/FromRevit/Pipe.cs
- Revit_Core_Engine/Convert/Environment/FromRevit/Space.cs
- Revit_Core_Engine/Convert/Environment/FromRevit/Wire.cs
- Revit_Core_Engine/Convert/FromRevit.cs
- Revit_Core_Engine/Convert/Revit/ToRevit/ViewPlan.cs
- Revit_Core_Engine/Query/DuctSectionProfile.cs
- Revit_Core_Engine/Query/DuctSectionProperty.cs
- Revit_Core_Engine/Query/DuctShape.cs
- Revit_Core_Engine/Query/OrientationAngle.cs
- Revit_Core_Engine/Query/PipeSectionProperty.cs
- Revit_Core_Engine/Query/Profile.cs
- Revit_Core_Engine/Query/SystemWorksetIds.cs
- Revit_Core_Engine/Revit_Core_Engine.csproj
Closes
#840 
#841 
#842 
#844 
#845 
#846 
[Revit and GS files](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue842%2DMEPConvertIssueFixes&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
Fixed the orientation angle to display the correct angle
Fixed descriptions 
Duct shapes derived from connectors in Revit 2018
Switch in DuctSectionProfile changed for compliance
Fixed unit conversion issue
Fixed an MEP SectionProperty issue
> Revit toolkit MEP Converts - Issue fixes

- README.md
Closes #856
Wiki update in the process, to be finished soon.
Not needed.
> Readme updated to reflect support for Revit 2021

- Revit_Core_Adapter/Revit_Core_Adapter.csproj
- Revit_Core_Engine/Revit_Core_Engine.csproj
- altConfigs.txt
Closes #870
Not needed, check if compiles and the files get copied over correctly.
> .csproj changed to make the assemblies land in BHoM/Assemblies folder on Debug/Release solution config

- Revit_Adapter/RevitAdapter.cs
- Revit_Core_Adapter/Listener/RevitListener.cs
https://github.com/BHoM/Socket_Toolkit/pull/83
Just make sure it still compile once you have changed on both PRs
@pawelbaran , there was no open PR that would interfere with this but let me know if it is a problem. We can easily delay this if needed.
> Align to namespace change in Socket Toolkit

- Revit_Core_Engine/Convert/FromRevit.cs
- Revit_Core_Engine/Convert/Structure/FromRevit/Bars.cs
- Revit_Core_Engine/Convert/Structure/FromRevit/Profile.cs
- Revit_Core_Engine/Query/BuiltInCategories.cs
- Revit_Core_Engine/Query/DuctSectionProfile.cs
- Revit_Core_Engine/Query/FramingElementProperty.cs
- Revit_Core_Engine/Query/PipeSectionProperty.cs
- Revit_Core_Engine/Query/Profile.cs
- Revit_Core_Engine/Revit_Core_Engine.csproj
https://github.com/BHoM/BHoM/pull/1030
https://github.com/BHoM/BHoM_Engine/pull/2063
Related to https://github.com/BHoM/BHoM/issues/756
- Aligning with migration of shape profiles from Geometry to Spatial
> Aligning with changes to ShapeProfiles

- Revit_Core_Engine/Convert/Architecture/FromRevit/Ceiling.cs
https://github.com/BHoM/BHoM/pull/1032
https://github.com/BHoM/BHoM_Engine/pull/2068
> Move towards using ceiling tiles for ceilings

- Revit_Core_Engine/Convert/Environment/FromRevit/Building.cs
https://github.com/BHoM/BHoM_Engine/pull/2141
Replaces Building object as the Building Create method has been removed
> Replace Building create method with object creation

- Revit_Core_Adapter/CRUD/Read.cs
- Revit_Core_Engine/Query/MaterialTakeOff.cs
- Revit_Core_Engine/Revit_Core_Engine.csproj
- Revit_Engine/Create/Config/RevitPullConfig.cs
- Revit_Engine/Query/MaterialTakeOff.cs
- Revit_Engine/Revit_Engine.csproj
- Revit_oM/Misc/RevitMaterialTakeOff.cs
- Revit_oM/Revit_oM.csproj
https://github.com/BHoM/BHoM/pull/1103
Closes #718
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue718%2DMaterialTakeoff&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - I have tested it with the basic architectural sample shipped together with Revit (_C:\Program Files\Autodesk\Revit 20XX\Samples\rac_basic_sample_project.rvt_), everything works fine (please see the .gh file + I've manually calculated total concrete volume of foundations and compared it to the extracted value). So the core functionality looks OK, would be nice if @enarhi and @michaelhoehn could stress-test it on the actual problems.
- support for …
> Support for pulling and querying element material take offs implemented

- Revit_Engine/Revit_Engine.csproj
- Revit_oM/Revit_oM.csproj
> All references set to copy local == false

- Revit_Engine/Query/RenderMeshes.cs
- Revit_Engine/Revit_Engine.csproj
Closes #927
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue927%2DRenderMeshes&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- `RenderMeshes` query method added
> RenderMeshes query method added

- Revit_Core_Engine/Convert/Geometry/ToRevit/CurveList.cs
https://github.com/BHoM/BHoM_Engine/pull/2231
Closes #866
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%23866%2DNurbsConvertBug%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit) - to be ran on an empty Revit model (please make sure the construction name in GH script is aligned with an existing floor type name in Revit).
- `ToRevit` nurbs curve convert fixed to return an approximate polyline instead of a distorted hermite spline
> ToRevit nurbs curve convert fixed to return an approximate polyline instead of a distorted hermite spline

- Revit_Core_Engine/Query/OpeningSurface.cs
Closes #958
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%23958%2DOpeningSurfaceBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
- opening surface edge case bug fixed
> Opening surface edge case bug fixed

- Revit_oM/Config/PullGeometryConfig.cs
- Revit_oM/Config/PullRepresentationConfig.cs
Closes #967
Run Grasshopper and try creating one of the subject objects - on `master` that is impossible, on this branch should work.
- `IObject` implemented to `PullGeometryConfig` and `PullRepresentationConfig`
> IObject implemented to PullGeometryConfig and PullRepresentationConfig

- Revit_Engine/Create/Config/RevitPullConfig.cs
Closes #1006
Not sure how to phrase that but... not needed 👼
> Deprecated 3.3 code removed

- Revit_Core_Engine/Modify/SetType.cs
- Revit_Core_Engine/Query/ElementType.cs
Closes #1011
_UpdateType.rvt_ and _UpdateType.gh_ on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPush&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - the bottom update has been added to verify this PR.
> String-based type update enabled

- Revit_Core_Engine/Convert/Revit/ToRevit/ViewPlan.cs
- Revit_Core_Engine/Create/BoundingRectangle.cs
- Revit_Core_Engine/Create/SectionBoundingBox.cs
- Revit_Core_Engine/Create/View/View3d.cs
- Revit_Core_Engine/Create/View/ViewPlan.cs
- Revit_Core_Engine/Create/View/ViewSection.cs
- Revit_Core_Engine/Query/ViewFamilyType.cs
- Revit_Core_Engine/Revit_Core_Engine.csproj
- dependencies.txt
Closes #1016 
Adds 6 new methods for users to create Floor Plan, Section and 3D views.
Added methods: 
`BH.Revit.Engine.Core.Create.ViewPlan`
`BH.Revit.Engine.Core.Create.ViewSection`
`BH.Revit.Engine.Core.Create.View3d`
`BH.Revit.Engine.Core.Create.RectangleBounding`
`BH.Revit.Engine.Core.Create.SectionBoundingBox`
`BH.Revit.Engine.Core.Query.ViewFamilyType`
None
> Revit_Core_Engine: Views creation expanded

- Revit_Core_Engine/Convert/Revit/ToRevit/ElementType.cs
- Revit_Core_Engine/Convert/Revit/ToRevit/ParameterElement.cs
- Revit_Core_Engine/Convert/ToRevit.cs
- Revit_Core_Engine/Create/CategorySet.cs
- Revit_Core_Engine/Create/Definition/Parameter.cs
- Revit_Core_Engine/Create/Definition/ProjectParameter.cs
- Revit_Core_Engine/Create/Definition/SharedParameter.cs
- Revit_Core_Engine/Modify/AddOrReplace.cs
- Revit_Core_Engine/Modify/SetParameter.cs
- Revit_Core_Engine/Query/CategoriesWithBoundParameters.cs
- Revit_Core_Engine/Revit_Core_Engine.csproj
- Revit_Engine/Compute/CloneType.cs
- Revit_Engine/Revit_Engine.csproj
- Revit_oM/Misc/ClonedType.cs
- Revit_oM/Parameters/ParameterDefinition.cs
- Revit_oM/Revit_oM.csproj
Not a direct dependency, but testing the colour parameter assignment requires building https://github.com/BHoM/BHoM_Engine/pull/2502.
Closes #993
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231027%2DProjectParametersAndRegionTypes&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - best to test with the Autodesk basic sample architecture project (_C:\Program Files\Autodesk\Revit 20XX\Samples\rac_basic_sample_project.rvt_). Please note that you may need to switch the shared parameters file to a new/empty one because the original is blocked (Revit_Toolkit will inform you about it).
Please feel free to do more stress testing and add …
> Parameter creation and cloning of element types enabled

- Revit_Core_Engine/Create/View/ViewReflectedCeilingPlan.cs
- Revit_Core_Engine/Revit_Core_Engine.csproj
Closes #1040 
To complement the create view methods we need one to create reflected ceiling plan.
Adds `BH.Revit.Engine.Core.Create.ViewReflectedCeilingPlan`
> Revit_Core_Engine: Add functionality to create reflected ceiling plan

- Revit_Core_Engine/Query/ElementType.cs
Closes #1050
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231051%2DSectionUpdateBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
> Section update issues resolved

- Revit_Engine/Modify/Transform.cs
> Revit_Toolkit: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone

- Revit_Core_Engine/Query/ElementIds/ElementIds.cs
- Revit_Core_Engine/Query/ElementIds/ElementIdsOfEverything.cs
- Revit_Core_Engine/Query/Passes.cs
- Revit_Core_Engine/Revit_Core_Engine.csproj
- Revit_Engine/Query/FilterDescription.cs
- Revit_Engine/Revit_Engine.csproj
- Revit_oM/Requests/FilterByParameterNumber.cs
- Revit_oM/Requests/FilterEverything.cs
- Revit_oM/Revit_oM.csproj
Closes #1068
Files to test the changes in `FilterByParameterNumber` are placed on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2FBuroHappold%5FRevit%5FToolkit%2D%23296%2DNEWScenarioBasedRoutinesPrototype&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
`FilterEverything` can be tested on any model - just be careful as pull of everything can take some time ;-)
- `FilterEverything` request introduced 
- `FilterDescription` query added
- `FilterByParameterNumber` extended with `ConvertUnits` property
> FilterEverything request introduced, FilterDescription query added, FilterByParameterNumber refined

- Revit_Core_Engine/Convert/Physical/ToRevit/Floor.cs
Not directly, but easier to review with https://github.com/BHoM/BHoM_Engine/pull/2608
Closes #1071
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231073%2DCreateFoundationSlabFix&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
> Push of Foundation Slabs enabled

- Revit_Core_Adapter/Listener/RevitListener.cs
Closes #1079
Strictly visual change - open Revit and see if the buttons look good.
> UI button layout tweaked

- Revit_Core_Engine/Compute/SplitRequestTreeByLinks.cs
- Revit_Core_Engine/Convert/Revit/ToRevit/ParameterElement.cs
- Revit_Core_Engine/Convert/ToRevit.cs
- Revit_Core_Engine/Modify/Postprocess.cs
- Revit_Engine/Modify/Transform.cs
- Revit_oM/Parameters/ParameterDefinition.cs
- Revit_oM/Versioning_43.json
Closes #1085
Sanity check .gh file uploaded to [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231086%2DMisalignedNamespaces&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4), but I believe a versioning check should be enough of a verification.
> Misaligned namespaces fixed

- Revit_Core_Engine/Create/FamilyInstance/FamilyInstance.cs
Closes #1089
Issue-specific test created by @ssiimmoonnee uploaded to [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231090%2DOneLevelBasedHostedFamilyBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
Standard test files _CreateUpdateIInstances.rvt_ and _CreateUpdateIInstances.gh_ from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPush&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
> OneLevelBased hosted family creation bug fixed

- Revit_Core_Engine/Create/CategorySet.cs
- Revit_Core_Engine/Create/CurveArray.cs
- Revit_Core_Engine/Create/Definition/Parameter.cs
- Revit_Core_Engine/Create/Definition/ProjectParameter.cs
- Revit_Core_Engine/Create/Definition/SharedParameter.cs
- Revit_Core_Engine/Create/FamilyInstance/AdaptiveComponent.cs
- Revit_Core_Engine/Create/Options.cs
- Revit_Core_Engine/Create/ReferencePlane.cs
- Revit_oM/Parameters/ParameterDefinition.cs
2nd part of #596
This PR is only about descriptions.
In the coming days, this PR will be followed with sister PRs covering other classes of Revit_Core_Engine.
> Create class of Revit_Core_Engine covered with descriptions

- Revit_Core_Engine/Modify/AddOrReplace.cs
- Revit_Core_Engine/Modify/NormalizeAngleDomain.cs
- Revit_Core_Engine/Modify/RemoveDuplicateAnalyticalElements.cs
- Revit_Core_Engine/Modify/RemoveEmptyPanelIds.cs
- Revit_Core_Engine/Modify/RemoveGridSegmentIds.cs
- Revit_Core_Engine/Modify/RemoveStackedWallParts.cs
- Revit_Core_Engine/Modify/SetIdentifiers.cs
- Revit_Core_Engine/Modify/SetTags.cs
- Revit_Core_Engine/Modify/SetType.cs
- Revit_Core_Engine/Modify/Update.cs
3rd part of #596
This PR is only about descriptions.
In the coming days, this PR will be followed with sister PRs covering other classes of Revit_Core_Engine.
> Modify class of Revit_Core_Engine covered with descriptions

- README.md
Closes #1061
Revit 2022 added to Readme.md - testing of readme should not be needed 🐒 
Wiki updated, this is the last bit.
> Revit 2022 added to Readme.md

- Revit_Core_Engine/Query/RenderMeshes.cs
https://github.com/BHoM/BHoM_Engine/pull/2606
Closes #1074
> Align to Graphics_oM `Vertex` to `RenderPoint` refactoring

- Revit_Core_Engine/Create/Solid.cs
- Revit_Core_Engine/Revit_Core_Engine.csproj
Closes #1121
Add method for creating solid extrusion from `IList<CurveLoop>` and `Filled Region` with bottom and top limitation.
> Add method for creating solid objects from list of boundaries and filled regions.

- Revit_Core_Adapter/Listener/RevitListener.cs
- Revit_Core_Adapter/RevitListenerAdapter.cs
Closes #1125
@kayleighhoude's reproductive issue plus [standard Revit tests](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
This is related to the change in assembly loading system introduced in https://github.com/BHoM/BHoM_Engine/pull/2681.
> Revit stability issues fixes

- Revit_Engine/Versioning_50.json
Closes #
Needed by https://github.com/BHoM/SAP2000_Toolkit/pull/241
> Legacy versioning fixed

- Revit_Core_Engine/Query/ClosestElement.cs
- Revit_Core_Engine/Query/HasLocation.cs
- Revit_Core_Engine/Query/LinkInstance.cs
- Revit_Core_Engine/Revit_Core_Engine.csproj
Closes #1123 
Closes #1133
Adds a method to query the closest element from another element, with the ability to filter by category and distance search radius.
N/A
Added `Core.Query.ClosestElement`
Added `Core.Query.HasLocation`
> Add method to query closest element from another element (REBASE)

- Revit_Core_Engine/Query/OpeningSurface.cs
Closes #1140
Try pulling walls using _FromLink_PullWallFloorRoofLocation.gh_ and _FromLink_PullPanelLocation.rvt_ from [this SharePoint folder](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull%2FFromLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
@FraserGreenroyd this is a oneliner that should be 100% safe - I am not desperate to see this merged before the Beta release, so I leave the decision about hitting the green button to you 👍
> Query.OpeningSurfaces_Curtain to use Create.PlanarSurface to generate output

- Revit_Core_Engine/Convert/Geometry/FromRevit/Grid.cs
- Revit_Core_Engine/Convert/Geometry/FromRevit/Level.cs
- Revit_Core_Engine/Convert/Geometry/ToRevit/Grid.cs
- Revit_Core_Engine/Convert/Geometry/ToRevit/Level.cs
- Revit_Core_Engine/Convert/ToRevit.cs
- Revit_Core_Engine/Modify/Postprocess.cs
- Revit_Core_Engine/Modify/SetLocation.cs
- Revit_Core_Engine/Query/BHoMType.cs
- Revit_Core_Engine/Query/Level.cs
https://github.com/BHoM/BHoM/pull/1347
https://github.com/BHoM/BHoM_Engine/pull/2732
Aligning with migration of objects and methods in BHoM and Engine
> Aligning with Grid and Level migration to Spatial

- Revit_Core_Engine/Modify/CopyParameters.cs
Closes #1145
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231155%2DCopyParametersFix&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
This is a bit of an edge case, but can be a pain when parameter mapping is used (see the test script).
> CopyParameters fixed to copy the properties independent of parameters

- Revit_Core_Adapter/Listener/AvailabilityClasses/AlwaysAvailable.cs
- Revit_Core_Adapter/Listener/RevitListener.cs
- Revit_Core_Adapter/Revit_Core_Adapter.csproj
Closes #1148
Open Revit and check whether the buttons are enabled before opening any document.
> Adapter buttons made always enabled

- Revit_Core_Engine/Convert/Structure/FromRevit/Bars.cs
Done is support of, but compiles without https://github.com/BHoM/BHoM_Engine/pull/2738
Align with removed methods from Structure_Engine
> Align with changes in Structure_Engine

- Revit_Engine/Query/Description.cs
- Revit_Engine/Revit_Engine.csproj
> Description(PropertyDifference) query added

- Revit_Core_Engine/Query/Intersection.cs
- Revit_Core_Engine/Query/Intersections.cs
- Revit_Core_Engine/Query/IsInRange.cs
- Revit_Core_Engine/Revit_Core_Engine.csproj
Closes #1182 
Methods has been added:
- `Intersection` - getting the intersection between Revit curves
- `IsInRange` - boolean intersection between bounding boxes
> Intersection methods added

- Revit_Core_Adapter/CRUD/Read.cs
- Revit_Core_Engine/Compute/OpenWorksetsPrefilter.cs
- Revit_Core_Engine/Query/AllWorksetIds.cs
- Revit_Core_Engine/Revit_Core_Engine.csproj
Closes #1188
Any monstrous file with worksets should suffice - @IsakNaslundBh should have one at hand 👍
> Prefiltering by workset optimised

- Revit_Core_Engine/Query/Insulation.cs
- Revit_Core_Engine/Revit_Core_Engine.csproj
Closes #1197 
Added `Insulation` method to get the insulation of the element.
> Add method to return the element insulation

- Revit_Adapter/Properties/AssemblyInfo.cs
- Revit_Core_Adapter/Properties/AssemblyInfo.cs
- Revit_Core_Engine/Properties/AssemblyInfo.cs
- Revit_Engine/Properties/AssemblyInfo.cs
- Revit_oM/_Properties/AssemblyInfo.cs
Update Assembly Information to include description
> Update Assembly Information

- Revit_Core_Engine/Query/Intersections.cs
Closes #1232 
Add `UVInterstections` method to return UV parameters of intersected curves.
New PR for #1233
> Add Intersection method to get UV points

- altConfigs.txt
> Missing altconfigs for 2023 added

- Revit_Core_Engine/Convert/Geometry/FromRevit/Point.cs
- Revit_Core_Engine/Convert/Geometry/FromRevit/Vector.cs
- Revit_Core_Engine/Convert/Geometry/ToRevit/XYZ.cs
> Performance of basic vector converts fixed

- Revit_Core_Engine/Convert/ToSI.cs
- Revit_Core_Engine/Query/SIMultiplier.cs
Closes #1303
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231329%2DUnitConversionPerformance&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
> Unit conversion performance improved

- Revit_Adapter/RevitAdapter.cs
- Revit_Core_Adapter/Listener/Forms/UpdatePortsForm.cs
- Revit_Core_Adapter/RevitListenerAdapter.cs
- Revit_Core_Engine/Create/View/ViewPlan.cs
- Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs
- Revit_Core_Engine/Objects/WarningSwallower.cs
- Revit_Core_Engine/Query/CableTraySectionProperty.cs
- Revit_Core_Engine/Query/CheckoutStatus.cs
- Revit_Core_Engine/Query/DuctSectionProperty.cs
- Revit_Core_Engine/Query/ElementIds/ElementIdsBySelection.cs
- Revit_Core_Engine/Query/ElementType.cs
- Revit_Core_Engine/Query/IsOwnedByOtherUser.cs
- Revit_Core_Engine/Query/LinkedElementsInView.cs
- Revit_Core_Engine/Query/RenderMeshes.cs
- Revit_Engine/Compute/SortByPerformance.cs
- Revit_Engine/Create/Config/RevitPushConfig.cs
- Revit_Engine/Modify/SetRevitParameter.cs
- Revit_Engine/Query/FamilyName.cs
Closes #1331 
- Compliance issues addressed.
> Documentation compliance issues

- Revit_oM/Attributes/CategoryDisciplineAttribute.cs
- Revit_oM/Attributes/CategoryTypeAttribute.cs
- Revit_oM/Enums/Category.cs
This will allow better filtering and management of the categories.
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231351%2DCategoryGrouping&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) are the Excel files that contain all categories grouped by type and discipline (lists generated by taking screenshots from Revit 2023 and extracting text, then postproc to create the tabular sets) - please feel free to compare against the list in Revit 👍 
5 internal categories added on top:
- assemblies
- model groups
- revisions
- schedules
- views
> New category attributes related to type and discipline added + category list cleaned up

- Revit_Core_Engine/Query/Parameters.cs
Closes #1359 
Method that returns all available and unique parameters of given elements.
> Add `Query.Parameters`

- Revit_Engine/Query/RevitToolkitWiki.cs
Closes #1363 
- created new Query method RevitToolkitWiki.cs to return updated URL (based on DocumentationURL inside BHoM_Engine)
- replaced URL link with call to new method inside Buttons/RevitToolkitWiki.cs
> Added `Query.RevitToolkitWiki` and updated wiki URL reference

- Revit_Core_Engine/Query/GeometryPrimitives.cs
Closes #1330
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%231330%2DTRF%20Non%20Conformal%20Error&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
Not desperate to get it in before the Beta release, but would be nice to have.
> Geometry extraction edge case fixed

- Revit_Engine/Compute/RevitDiffing.cs
Closes #1378
Documentation changes only.
> Documentation issues fixed

- Revit_Core_Engine/Create/FamilyInstance/FamilyInstance.cs
- Revit_Core_Engine/Modify/SetLocation.cs
Closes #1376
See https://github.com/BHoM/Revit_Toolkit/issues/1376
> Creation and update of workplane-based family instances bugfixed

- Revit_Core_Engine/Create/View/Callout.cs
Closes #1397 
Add method for creating callout view.
> Add `Create.Callout`

- Revit_Core_Engine/Create/View/ViewSection/ViewSection.cs
- Revit_Core_Engine/Query/OrientationAngle.cs
- Revit_Core_Engine/Query/TrussPlane.cs
- Revit_Core_Engine/Query/ViewBox.cs
> Methods to create section boxes and views refined plus truss plane query added

- Revit_Core_Engine/Query/ConnectorsOfType.cs
- Revit_Core_Engine/Query/OrientationAngle.cs
Closes #1410
Standard MEP element pull test procedure
> MEP element orientation issues fixed

- Revit_Core_Engine/Convert/Revit/Internal/ToSolid.cs
- Revit_Core_Engine/Query/Bounds.cs
- Revit_Core_Engine/Query/TaggedElements.cs
A mashup of a few minor tweaks and additions that accumulated on my machine while working on different bits:
- Query method for elements tagged by a given tag
- consolidation of `ToSolid` internal convert
- method to get bounds of a group of Revit points (mirror of a Geometry_Engine method added to avoid converts to BHoM and back, performance reasons)
> Minor tweaks and additions to the code base

- Revit_Core_Adapter/Listener/RevitListener.cs
- Revit_Engine/Query/RevitToolkitWiki.cs
Closes #1424
Open Revit and check if the adapter buttons work as expected.
I could not stop myself from a little code tweak to avoid hardcoded class names.
> Wiki link updated

- Revit_oM/Config/RevitComparisonConfig.cs
Closes #1430
Standard diffing test procedure
...I thought I will PR that tweak as I already had it ready on my local - happy to put the PR down if we end up disagreeing with the idea 😉
> 'Edited by' added to the default blacklist in diffing

- Revit_Engine/Compute/RevitDiffing.cs
https://github.com/BHoM/BHoM/pull/1583
> Align to Diffing_oM change of Id to ID

- Revit_Core_Engine/Query/GeometryPrimitives.cs
Closes #1437
See https://github.com/BHoM/Revit_Toolkit/issues/1437
> Removed room/space geometry bug fixed

- Revit_Core_Engine/Query/DoesIntersect.cs
Closes #1435 
Add bbox check before solid check to improve performance.
> `DoesIntersect` - add bbox check

- Revit_Core_Engine/Query/CloudGuids.cs
- Revit_Core_Engine/Query/CloudProjectAndModelGuids.cs
> Method to query cloud guids added

- Revit_Core_Engine/Query/IsPrimaryDesignOption.cs
Closes #1448 
- add IsPrimaryDesignOption Wrapper
> IsPrimaryDesignOption Wrapper

- Revit_Core_Engine/Create/CurveLoop.cs
- Revit_Core_Engine/Modify/Project.cs
- Revit_Core_Engine/Query/Bounds.cs
- Revit_Core_Engine/Query/PlanViewRange.cs
- Revit_Core_Engine/Query/ViewSolid.cs
> View queries added

- Revit_Core_Engine/Objects/ActiveViewVisibilityContext.cs
Closes #1450 
I added the null handler.
Given the PR's scope, code review should be enough?
> Handle null exception when querying unloaded links

- Revit_Core_Engine/Query/Bounds.cs
- Revit_Core_Engine/Query/ViewSolid.cs
> View solid and bounds fixed for sections without far clipping

- Revit_Core_Engine/Query/ConnectedElements.cs
- Revit_Core_Engine/Query/Connectors.cs
Closes #1476 
Fixed duplicated elements bug.
> `ConnectedElements` - duplicate elements bugfix, `Connectors` method added

- Revit_Core_Engine/Query/ElementsInPath.cs
Closes #1479 
Added methods returning elements in path (elements between starting and ending element in MEP network)
> Elements In Path

- Revit_Core_Engine/Query/DoesIntersect.cs
Closes #148 
Added try/catch to avoid raising exception. Method should return false and exception message.
> DoesIntersect - intersection between solids bug fix

- Revit_Core_Engine/Query/GeometryPrimitives.cs
Closes #1484
Edge case captured by @michal-pekacki in one of the project models - to be tested against it.
> Conformal transformation bug fixed in geometry primitives query

- Revit_Core_Engine/Query/ElementsInPath.cs
Closes #1489 
Replace `HashSet<int>` with `List<ElementId>` to keep correct elements order.
> Elements In Path - incorrect order bug fix

- Revit_Core_Engine/Query/Bounds.cs
- Revit_Core_Engine/Query/LinkedElementsInView.cs
- Revit_Core_Engine/Query/PlanViewRange.cs
- Revit_Core_Engine/Query/ViewSolid.cs
Closes #1494 
Added `LinkedElementsInView` that works for any `View`.
> Update `LinkedElementsInView` method

- Revit_Engine/Create/Generic/RevitFilePreview.cs
Closes #1513
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231514%2DScrapeTxtInFamilyLibrary) - download the family together with .txt, then update the script to point at the folder containing them, check if all family types are scraped.
> Family library Create method tweaked to scrape type names from .txt file

- Revit_Core_Engine/Query/PanelSurfaces.cs
Closes #1535
See https://github.com/BHoM/Revit_Toolkit/issues/1535
> Pull of walls hosted by other walls fixed

- Revit_Core_Engine/Convert/Revit/FromRevit/Parameter.cs
- Revit_Core_Engine/Query/IsEnumParameter.cs
Closes #1538
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231539%2DEnumConvertBug) - please test against _all_ versions of Revit.
> Enum convert fix for Revit 2021

- Revit_Core_Engine/Query/ElementIds/ElementIdsByCondition.cs
Closes #1540 
Added  null check to avoid crashing errors when element has no bhom type.
> `AddParameterMapping` - null check added

- Revit_Core_Engine/Compute/TryGetValueFromSource.cs
- Revit_Core_Engine/Query/ElementIds/ElementIds.cs
- Revit_Core_Engine/Query/ElementIds/ElementIdsByCondition.cs
- Revit_Core_Engine/Query/ElementIds/ElementIdsByParameterExistence.cs
- Revit_Core_Engine/Query/ParameterValue.cs
Closes #1542
Standard requests => filtering by elementId and parameters. Plus UT on top of that.
> Filtering by ElementId fixed

- Revit_Core_Engine/Compute/CompareValues.cs
- Revit_Core_Engine/Compute/TryGetValueFromSource.cs
- Revit_Core_Engine/Query/FormulaComponent.cs
- Revit_Core_Engine/Query/HasValue.cs
- Revit_Core_Engine/Query/ParameterValue.cs
https://github.com/BHoM/BHoM_Engine/pull/3475
Closes #1545
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2FRevit%5FToolkit%2D%231545%2DFilteringByElementIdBug)
> Filtering fixed

- Revit_Core_Engine/Convert/Revit/ToRevit/CurveElement.cs
- Revit_Core_Engine/Create/ModelCurve.cs
- Revit_Core_Engine/Create/Plane.cs
- Revit_Core_Engine/Create/SketchPlane.cs
- Revit_Core_Engine/Modify/CleanUp.cs
- Revit_Core_Engine/Query/AlignedBoundingBox.cs
- Revit_Core_Engine/Query/Centroid.cs
- Revit_Core_Engine/Query/CornerPoints.cs
- Revit_Core_Engine/Query/Distance.cs
- Revit_Core_Engine/Query/LocalCoordinateSystem.cs
- Revit_Core_Engine/Query/LocationCurve.cs
- Revit_Core_Engine/Query/PlaneIntersections.cs
- Revit_Core_Engine/Query/Proximity.cs
- Revit_Core_Engine/Query/Segments.cs
Closes #
For framing and column location curve: UTs, rest in the test project.
> Utility methods added and tweaked

- Revit_Core_Engine/Compute/TryGetValueFromSource.cs
- Revit_oM/Parameters/ParameterValueSource.cs
Closes #1557
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231558%2DNullableFromType) - script to be run against the sample arch model
> ParameterValueSource.FromType made nullable

- Revit_Core_Engine/Convert/Revit/FromRevit/ParameterDefinition.cs
Closes #1584
Confirming that the code compiles should be enough of verification.
@michal-pekacki apologies for the volume of changes shown by github - it is only about formatting, the actual change is just a few lines (ideally just compare it yourself in notepad++ or temp tweak the code)
> Compilation issues fixed

- Revit_Core_Engine/Convert/Structure/FromRevit/Panels.cs
- Revit_Core_Engine/Query/AnalyticalOutlines.cs
- Revit_Core_Engine/Query/PanelSurfaces.cs
Closes #1598
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231599%2DOutlineExtractionIssues)
> Issues related to nurbs outlines fixed
