BHoM/Revit_Toolkit

Adapter_Revit_UI/Read/Read.cs
Revit_Engine/Convert/FilterQuery.cs
Revit_Engine/Modify/SetPullEdges.cs
Revit_Engine/Query/IncludeNonVisibleObjects.cs
Revit_Engine/Revit_Engine.csproj

Include Non Visible Objects when pulling edges of Revit Element
Closes #244

Revit_Toolkit - Issue 244 - Include Non Visible Objects

---

Adapter_Revit_UI/Create/Create.cs
Adapter_Revit_UI/Read/Read.cs
Adapter_Revit_UI/RevitUIAdapter.cs
Engine_Revit_UI/Compute/Errors.cs
Engine_Revit_UI/Compute/Warnings.cs
Engine_Revit_UI/Convert/Common/ToRevit/Element.cs
Engine_Revit_UI/Convert/Geometry/ToBHoM/ICurve.cs
Engine_Revit_UI/Convert/Geometry/ToRevit/CoordinateSystem.cs
Engine_Revit_UI/Convert/Geometry/ToRevit/Curve.cs
Engine_Revit_UI/Convert/Structure/ToBHoM/FramingElement.cs
Engine_Revit_UI/Convert/Structure/ToRevit/FamilyInstance.cs
Engine_Revit_UI/Query/BottomLevel.cs
Revit_Engine/Convert/AdapterID.cs
Revit_Engine/Create/Settings/GeneralSettings.cs
Revit_Test/Test.cs
Revit_UI/RevitListener.cs
Revit_oM/Enums.cs
Revit_oM/Settings/GeneralSettings.cs

[BHoM #421](https://github.com/BHoM/BHoM/pull/421)
Closes #241
Closes #242 
Closes #235
Closes #251 
Failure Processing added
Undefined Discipline added
Pull for Undefined discipline updated (pull as GenericObject and DraftingObject)
Implements workaround for #235 - Pull Framing Element as GenericObject and gets Location Curve
Implements GenericObject Push for Structural Families
Change FramingElement LocationCurve from Line to ICurve to align with [BHoM Pull Request 421](https://github.com/BHoM/BHoM/pull/421)
Warning added for pull GenericObject

Revit_Toolkit - Issue241 - GenericObject Updates

---

Adapter_Revit_UI/Create/Environment/BuildingElement.cs
Adapter_Revit_UI/Delete/Delete.cs
Engine_Revit_UI/Convert/Environment/ToBHoM/BuildingElement.cs
Engine_Revit_UI/Convert/Environment/ToBHoM/BuildingElementProperties.cs
Engine_Revit_UI/Convert/Environment/ToBHoM/ElementProperties.cs
Engine_Revit_UI/Convert/Environment/ToRevit/Element.cs
Engine_Revit_UI/Convert/Environment/ToRevit/ElementType.cs
Engine_Revit_UI/Convert/ToBHoM.cs
Engine_Revit_UI/Convert/ToRevit.cs
Engine_Revit_UI/Engine_Revit_UI.csproj
Engine_Revit_UI/Query/BHoMTypes.cs
Revit_Engine/Create/Elements/BuildingElement.cs
Revit_Engine/Modify/SetFamilyName.cs
Revit_Engine/Modify/SetFamilyTypeName.cs

https://github.com/BHoM/BHoM_Engine/pull/851
Fixes #252 
Removes references to deprecated properties of Environment_oM
All of @michaldengusiak previous test scripts
- Removed references to deprecated properties from Environment_oM

Revit toolkit deprecated properties

---

Engine_Revit_UI/Query/BuiltInCategory.cs
Engine_Revit_UI/Query/ElementIds.cs

Fix for CategoryFilter and TypeNameFilter. Enable to pull Space Types and similar kinds of objects
Closes #284 
[Dynamo script and Sample Model](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue284-PullSpaceTypes?csf=1&e=O6c3fg)

Revit_Toolkit-Issue284-PullSpaceTypes

---

Engine_Revit_UI/Query/Outlines.cs

[#979](https://github.com/BHoM/BHoM_Engine/pull/979)
Closes #304 
No additional test file needed.
Updated:
- Outlines
Join() is being moved from BH.Engine.Geometry.Modify to BH.Engine.Geometry.Compute, what requires changes in calls to avoid ambiguity.

Revit_Toolkit - issue 304: Update calling of Join() to match changes in Bhom_Engine

---

Adapter_Revit_UI/Create/Create.cs
Engine_Revit_UI/Engine_Revit_UI.csproj
Engine_Revit_UI/Modify/LoadFamilySymbol.cs
Engine_Revit_UI/Modify/SetIdentifiers.cs
Engine_Revit_UI/Query/FamilyPlacementTypeName.cs
Engine_Revit_UI/Query/FamilySymbols.cs
Engine_Revit_UI/Query/RevitTypes.cs
Revit_Engine/Convert/AdapterID.cs
Revit_Engine/Create/Generic/RevitFilePreview.cs
Revit_Engine/Query/Family.cs
Revit_Engine/Query/FamilyName.cs
Revit_Engine/Query/FamilyPlacementTypeName.cs
Revit_Engine/Query/Paths.cs
Revit_Engine/Query/RevitFilePreviews.cs
Revit_Engine/Revit_Engine.csproj
Revit_oM/Generic/RevitFilePreview.cs

Functionality to Load multiple families and place FamilySymbols
PR related to #261 
Sample script and families for tests saved [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue261-ProfileExtraction?csf=1&e=d0JR1k)
RevitFilePreview Push loads family
Revit_Toolkit Family PlacementType information added
Path property added to RevitFilePreview
RevitFilePreview to Revit_Toolkit Family method added
RevitFilePreview Paths method updated to pull unique path only

Revit_Toolkit-Issue261-ProfileExtraction

---

Engine_Revit_UI/Convert/Structure/ToRevit/FamilyInstance.cs

Closes #287 
No test file as the fix is quite obvious.

Revit_Toolkit-Issue287-FamilySymbolOfStructuralFramingBug

---

Adapter_Revit_UI/Adapter_Revit_UI.csproj
Engine_Revit_UI/Engine_Revit_UI.csproj
Revit_UI/Files/BHoM_2018.Addin
Revit_UI/Files/BHoM_2019.Addin
Revit_UI/RevitListener.cs
Revit_UI/Revit_UI.csproj

N/A
Closes #272 
- BHoM.Addin split into two files (version dependent) - temporary solution
- UI dll prefixed with version of Revit
No test files needed. Test procedure: 
- Build Revit_Toolkit
- Ensure files are moved to correct location (%AppData%\BHoM\Assemblies)
- Run Revit (2018 and 2019)
- Run Dynamo/Grashopper and make sure BHoM is loaded
- Do test pull/push
- Adapter_Revit_UI.csproj (Assembly name updated)
- Engine_Revit_UI.csproj (Assembly name updated)
- BHoM.Addin replaced by BHoM_2018.Addin and BHoM_2019.Addin
- RevitListener.cs (Directory of Assemblies updated to default)
- Revit_UI.csproj (Post-buid command and assembly names updated)
N/A

Revit_Toolkit - Issue272 - Assemblies To AppData

---

Revit_Engine/Create/Generic/RevitFilePreview.cs
Revit_Engine/Query/CategoryName.cs
Revit_Engine/Query/FamilyTypeNames.cs
Revit_Engine/Query/OmniClass.cs
Revit_Engine/Query/XDocument.cs
Revit_Engine/Revit_Engine.csproj
Revit_oM/Generic/RevitFilePreview.cs

N/A
Closes #311 
Test file can be found here: [link](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue311-ObjectSerialization?csf=1&e=7qw2Em)
- XDocument property removed from RevitFilePreview
- Static Query methods added for OmniClass, FamilyTypeNames and CategoryName of XDocument
- XDocument Query added for RevitFilePreview
N/A

Revit_Toolkit - Issue 311 - Remove property objects which cannot be serialised 

---

Engine_Revit_UI/Convert/Structure/ToBHoM/Profile.cs

Fixes #332 
Related to #333 
Added a missing '!' which caused channel sections to be pulled as freeform profiles
Re-ordered the search list for flange width to place b, B and bf before w, W, and D, as those are more likely to describe weight and depth of a section, respectively.
Any Revit pull of UK or US C-Channel sections should yield expected results.

Update Profile.cs to fix channel section pull

---

Adapter_Revit_UI/Adapter_Revit_UI.csproj
Engine_Revit_UI/Engine_Revit_UI.csproj
Revit_UI/Revit_UI.csproj

Fixes #354 
See DynamoToolkit issue https://github.com/BHoM/Dynamo_Toolkit/issues/159
- Changed Nuget DLLs to not copy local

Revit_Toolkit: Preventing copy local of DLLs from Nuget

---

Revit_Engine/Query/XDocument.cs

N/A
Closes #336
RevirFilePreview could not be created due to invalid check on file path
[Test script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue336-FamilyLibraryError?csf=1&e=Pzd13B)
XDocument.cs updated
N/A

Revit_Toolkit - Issue 336 - FamilyLibrary Load Error

---

Engine_Revit_UI/Convert/Architecture/ToBHoM/Ceiling.cs

N/A
Closes #367 
Convert method for Ceiling updated to include geometry
To be provided by @michaldengusiak 
- `Convert.ToBHoMCeiling(this Ceiling ceiling, PullSettings pullSettings = null)` method updated to include geometry
N/A

Revit_Toolkit - #367 -Missing Ceiling Geometry

---

Revit_Engine/Query/ElementIds.cs

N/A
Closes #283 
- pulling collection of Ids updated for SelectionFilterRequest
Uploaded to [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue283%2DPullUsingElementIds).
- Query.ElementIds([...]) updated for the case where enumerable of Id is stored as object enumerable (this happens in Grasshopper)
N/A

Revit_Toolkit - #312 - Physical Objects

---

Revit_UI/Revit_UI.csproj

N/A
Closes #377
N/A
- Revit_UI.csproj updated to not copy UI_PostBuild.exe
N/A

Set Copy Local false

---

Engine_Revit_UI/Convert/Geometry/ToRevit/Curve.cs
Revit_Engine/Query/CategoryNames.cs

Closes #387 
Null catch to prevent the code from crashing - instead an informative error is returned.
Test file located [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=WVbMGt&cid=7e1be85d%2D59b2%2D45f4%2D8d1b%2Da30668a3a29a&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue387%2DCategoryNamesCrashOnNull).
Informative error given when requested family type does not exist in the Revit document.

Null check for familyLibrary in CategoryNames query method

---

Engine_Revit_UI/Compute/Warnings.cs
Engine_Revit_UI/Convert/Geometry/ToRevit/Brep.cs
Engine_Revit_UI/Convert/Geometry/ToRevit/Curve.cs
Engine_Revit_UI/Convert/Revit/ToRevit/CurveElement.cs
Engine_Revit_UI/Convert/Revit/ToRevit/Element.cs
Engine_Revit_UI/Engine_Revit_UI.csproj
Revit_Engine/Create/Elements/ModelInstance.cs

[#603](https://github.com/BHoM/BHoM/pull/603)
[#1319](https://github.com/BHoM/BHoM_Engine/pull/1319)
Closes #408 
Test files are located on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%2FGeometry%5FoM%2DIssue425%2DCreationOfTrimmedNurbsSurfaceDefinition). To run it, please switch to the branches related to the following PRs:
- [#603 ](https://github.com/BHoM/BHoM/pull/603)
- [#1319](https://github.com/BHoM/BHoM_Engine/pull/1319)
- [#122](https://github.com/BHoM/Rhinoceros_Toolkit/pull/122)
- [#435](https://github.com/BHoM/Grasshopper_Toolkit/pull/435)
- [#435](https://github.com/BHoM/Revit_Toolkit/pull/435)
- …

Enable pushing surface-based ModelInstances

---

Engine_Revit_UI/Convert/Revit/ToRevit/CurveElement.cs

Closes #434
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue434%2DLinearityCheckIssue) - try pushing the object to any model.

Incorrect Linearity Check Fixed

---

Adapter_Revit_UI/CRUD/Read.cs
Engine_Revit_UI/Query/Discipline.cs
Revit_Engine/Query/DefaultDiscipline.cs
Revit_Engine/Query/Discipline.cs

Closes #457 
Closes #468 
Changes as in the changelog + I made an (hopefully successful) attempt to simplify the code.
- [whole issue](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue457%2DDisciplineQueryCleanup) - file with suffix _master_ will work correctly on both master and PR branch, while the one with suffix _PR_ will work only on master (some stuff got exposed to the UI)
- [extracted infinite loop bug](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%2 …

Query.Discipline Cleaned Up

---

Engine_Revit_UI/Modify/SetCustomData.cs

Closes #490
One can e.g. pull wall panels from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPull%2FStructure) and look up _Unconnected Height_ parameter - it is ~10ft instead of 3m prior to this fix.
Sorry for the late catch and thanks @rboulton-BH @FraserGreenroyd for flagging it up 👍

Unit conversion fixed on pull

---

Adapter_Revit_UI/CRUD/Read.cs
Engine_Revit_UI/Convert/Geometry/ToBHoM/Grid.cs
Engine_Revit_UI/Convert/Geometry/ToRevit/Grid.cs
Engine_Revit_UI/Convert/ToBHoM.cs
Engine_Revit_UI/Query/BHoMTypes.cs
Engine_Revit_UI/Query/BuiltInCategories.cs
Engine_Revit_UI/Query/RevitTypes.cs

Closes #23
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue23%2DMultiSegmentGrids).
- push and pull of multi segment grids has been enabled
Due to structure of Revit's object model (see [this](https://www.revitapidocs.com/2020/706e504e-20dd-e017-6bdf-e5265848d150.htm) and [this](https://www.revitapidocs.com/2020/47888507-2d69-664a-ead4-e481c7c5f42d.htm)), I needed to implement a workaround in `Read` file. Would be good to civilize it when working on simplifying the Toolkit.
https://github.com/BHoM/Revit_Toolkit/blob/5a6ab0b465e391fa8dd78073dce947e322f69bc4/Adapter_Revit_UI/CRUD/Read …

Push and pull of multi segment grids enabled

---

Revit_Engine/Query/FilterByType.cs
Revit_Engine/Revit_Engine.csproj

Closes #543 
Not needed
- `BH.Engine.Adapters.Revit.Query.FilterByType(IEnumerable<object>, Type)` has been deprecated as it is a duplicate of same method in `BH.Engine.Base.Query`

FilterByType method deprecated

---

Engine_Revit_UI/Convert/Physical/ToBHoM/Construction.cs
Engine_Revit_UI/Convert/ToBHoM.cs

Closes #542
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue542%2DUnnecessaryToBHoMConstruction) - this will work with any (even empty) Revit file.
- `ToBHoMConstruction` method has been unified and made work on any types that inherit from `Autodesk.Revit.DB.HostObjAttributes` when converted to BHoM

Boilerplate ToBHoMConstruction removed

---

Adapter_Revit_UI/CRUD/Delete.cs
Adapter_Revit_UI/CRUD/Read.cs
Engine_Revit_UI/Engine_Revit_UI.csproj
Engine_Revit_UI/Modify/RemoveGridSegmentIds.cs

Closes #515
Closes #557 
[#515](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue23%2DMultiSegmentGrids)
[#557](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue557%2DDeleteThenCreatePushIssue)
- Bug causing pushing an object with `PushType == PushType.DeleteThenCreate` return no output when nothing gets deleted prior to creation has been fixed
- Removal of unnecessary ids from elementId list in case of …

DeleteThenCreate Push bug fix & cleanup of MultiSegmentGrids Pull

---

Engine_Revit_UI/Convert/Environment/ToBHoM/Building.cs
Engine_Revit_UI/Convert/Environment/ToBHoM/EnergyAnalysisModel.cs
Engine_Revit_UI/Convert/ToBHoM.cs
Engine_Revit_UI/Engine_Revit_UI.csproj
Engine_Revit_UI/Query/ElementIds/ElementIds.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsEnergyAnalysisModel.cs
Revit_Engine/Query/Discipline.cs
Revit_oM/Requests/EnergyAnalysisModelRequest.cs
Revit_oM/Revit_oM.csproj

Closes #566 
[This script](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue566%2DToBHoMBuilding) with [this model](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPull%2FEnvironment%2FFrom%20MajaLindroth).
- `EnergyAnalysisModelRequest` allowing pull of the energy analysis model has been implemented
- `ProjectInfo.ToBHoMBuilding` allowing conversion of `Autodesk.Revit.DB.ProjectInfo` to …

Pull of Energy Analysis model refactored

---

Revit_Engine/Query/IsZero.cs

Closes #532
Not needed
- `BH.Engine.Adapters.Revit.Query.IsZero(double)` method has been deprecated

BH.Engine.Adapters.Revit.Query.IsZero(double) deprecated

---

Adapter_Revit_UI/CRUD/Delete.cs
Adapter_Revit_UI/CRUD/Read.cs
Engine_Revit_UI/Modify/RemoveGridSegmentIds.cs

Closes #583
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue583%2DEmptyIdCollection) - just open an empty Revit model, select nothing and try to pull, after fix the error below should disappear:
Please note that the error may be covered by an empty config note due to [Grasshopper_Toolkit #480](https://github.com/BHoM/Grasshopper_Toolkit/issues/480).
There might be a conflict with #577 - I will be happy to let it go first as it is much more serious than this one.

Read and Delete stopped from crashing on empty ElementId collection

---

Adapter_Revit_UI/AdapterActions/Pull.cs
Adapter_Revit_UI/AdapterActions/Push.cs
Adapter_Revit_UI/AdapterActions/Remove.cs
Adapter_Revit_UI/Modify/SetTags.cs
Engine_Revit_UI/Compute/Notes.cs
Engine_Revit_UI/Query/ElementIds/ElementIds.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByParameter.cs
Revit_Engine/Modify/DefaultIfNull.cs

Closes #544
Closes #586
Test file on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue544%2DTags) - it can be run with an empty Revit model based on structural template.
- Tags were refactored in order to follow the adapter changes: now they get added/updated correctly, also appear on pull. Separator between multiple tags in Revit changed from breaking line (_\n_) to semicolon plus space (_; _) for preview purposes.
- Any Notes generated by Revit_Toolkit were elevated to Warnings following [Grasshopper_Toolkit #480](https://github.com/BHoM/Grasshopper_Toolkit/issues/480)
This PR is …

Tags revisited and Notes changed to Warnings

---

Adapter_Revit_UI/AdapterActions/Push.cs
Adapter_Revit_UI/CRUD/Create.cs
Adapter_Revit_UI/CRUD/Delete.cs
Adapter_Revit_UI/CRUD/Read.cs
Adapter_Revit_UI/CRUD/Update.cs
Revit_Adapter/AdapterActions/Pull.cs
Revit_Adapter/AdapterActions/Push.cs
Revit_Adapter/AdapterActions/Remove.cs
Revit_Adapter/RevitAdapter.cs
Revit_UI/EventHandlers/Pull.cs
Revit_UI/EventHandlers/Push.cs
Revit_UI/EventHandlers/Remove.cs

[BHoM Adapter #214](https://github.com/BHoM/BHoM_Adapter/pull/214)
Closes #604
Closes #605 
Closes #606 
Closes #607 
[#604](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue604%2DFullPush)
#605 does not require a test file
[#606 and #607](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue606%2C607%2DNullReferenceHandlers)
- the code has been aligned to the change from `PushType.FullCRUD` to …

FullCRUD renamed to FullPush and error handling fixes

---

Adapter_Revit_UI/AdapterActions/Pull.cs
Adapter_Revit_UI/AdapterActions/Push.cs
Adapter_Revit_UI/AdapterActions/Remove.cs
Engine_Revit_UI/Compute/Notes.cs
Revit_Adapter/AdapterActions/Pull.cs
Revit_Adapter/AdapterActions/Remove.cs
Revit_Engine/Modify/DefaultIfNull.cs

Depends on [Grasshopper_Toolkit #490](https://github.com/BHoM/Grasshopper_Toolkit/pull/490), but will compile without it (so CI should not complain).
Closes #597
Closes #611
- [#597](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue597%2DRecordNote) to be used with Revit file from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPull%2FRevit%2FRequests)
- …

RecordNote calls uncommented and empty IRequest check added

---

Revit_Adapter/RevitAdapter.cs
Revit_Engine/Modify/DefaultIfNull.cs
Revit_oM/Elements/DraftingInstance.cs
Revit_oM/Elements/Family.cs
Revit_oM/Elements/ModelInstance.cs
Revit_oM/Elements/Sheet.cs
Revit_oM/Elements/ViewPlan.cs
Revit_oM/Elements/Viewport.cs
Revit_oM/Enums/AdapterMode.cs
Revit_oM/Enums/Discipline.cs
Revit_oM/Enums/NumberComparisonType.cs
Revit_oM/Enums/RevitViewType.cs
Revit_oM/Enums/TextComparisonType.cs
Revit_oM/Generic/FamilyLibrary.cs
Revit_oM/Generic/RevitFilePreview.cs
Revit_oM/Generic/TypeMap.cs
Revit_oM/Interface/IInstance.cs
Revit_oM/Interface/IParameterRequest.cs
Revit_oM/Interface/IView.cs
Revit_oM/Properties/InstanceProperties.cs
Revit_oM/Revit_oM.csproj
Revit_oM/Settings/ConnectionSettings.cs
Revit_oM/Settings/FamilyLoadSettings.cs
Revit_oM/Settings/MapSettings.cs
Revit_oM/Settings/RevitSettings.cs

Closes #613
First part o #595, the rest will follow on Monday.
Not needed.
- missing descriptions have been added to Revit_oM and Revit_Adapter
- legacy `BH.oM.Adapters.Revit.Enums.AdapterMode` has been deprecated
There is one conflict with #612, but same changes have been made to the file on both branches, so I believe it will be fine.

Descriptions added to Adapter and oM, AdapterMode deprecated

---

Revit_Engine/Compute/SortByPerformance.cs
Revit_Engine/Create/Config/RevitPullConfig.cs
Revit_Engine/Create/Config/RevitPushConfig.cs
Revit_Engine/Create/Config/RevitRemoveConfig.cs
Revit_Engine/Create/Elements/BHoMObject.cs
Revit_Engine/Create/Elements/DraftingInstance.cs
Revit_Engine/Create/Elements/ModelInstance.cs
Revit_Engine/Create/Elements/Sheet.cs
Revit_Engine/Create/Elements/ViewPlan.cs
Revit_Engine/Create/Elements/Viewport.cs
Revit_Engine/Create/Generic/FamilyLibrary.cs
Revit_Engine/Create/Generic/RevitFilePreview.cs
Revit_Engine/Create/Generic/TypeMap.cs
Revit_Engine/Create/Properties/InstanceProperties.cs
Revit_Engine/Create/Settings/ConnectionSettings.cs
Revit_Engine/Create/Settings/FamilyLoadSettings.cs
Revit_Engine/Create/Settings/MapSettings.cs
Revit_Engine/Create/Settings/RevitSettings.cs
Revit_Engine/Modify/AddMap.cs
Revit_oM/Elements/DraftingInstance.cs
Revit_oM/Elements/ModelInstance.cs
Revit_oM/Generic/RevitFilePreview.cs
Revit_oM/Settings/MapSettings.cs

Closes #615
Second part o #595, `Modify` and `Query` still need a refresh.
- `BH.Engine.Adapters.Revit.Compute` and `BH.Engine.Adapters.Revit.Create` descriptions added and/or refreshed
`BH.Engine.Adapters.Revit.Create.BHoMObject` deprecated

Revit_Engine: Compute and Create descriptions added and Create.BHoMObject deprecated

---

Engine_Revit_UI/Query/BHoMUnitType.cs

Closes #656
Closes #657
Test set on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssues656%2C657%2DUnitConverts).
The method is supported by two `private` arrays and a `private` dictionary - this is in order to get as close to unitless SI as possible. Could not come up with anything neater. Happy to discuss other approaches if any proposed.

Unit converts made robust and informative 

---

Engine_Revit_UI/Engine_Revit_UI.csproj
Engine_Revit_UI/Query/BoundingBox.cs

Closes #647
Rather not needed.
The only file using Common_Engine reference was doing a geometrical query that could be replaced with Geometry_Engine. Therefore, Spatial_Engine has not been referenced.

Reference to Common_Engine removed

---

Engine_Revit_UI/Modify/SetCustomData.cs
Revit_Engine/Query/WorksetId.cs

Closes #632
Closes #633
Closes #660
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssues632%2C660%2DEnumerableParameters), using model from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPull%2FRevit%2FRequests)
Workset name sits under _Workset_ `CustomData` key - it can be easily queried using `GetProperty`.

Saving enumerable parameters as strings in CustomData fixed

---

Adapter_Revit_UI/Adapter_Revit_UI.csproj
Adapter_Revit_UI/CRUD/Read.cs
Adapter_Revit_UI/CRUD/RenderMesh.cs
Engine_Revit_UI/Convert/Geometry/FromRevit/Mesh.cs
Engine_Revit_UI/Convert/Geometry/FromRevit/MeshFace.cs
Engine_Revit_UI/Engine_Revit_UI.csproj
Engine_Revit_UI/Query/FaceTriangulationFactor.cs
Engine_Revit_UI/Query/Meshes.cs
Engine_Revit_UI/Query/Representation.cs
Engine_Revit_UI/Query/ViewDetailLevel.cs
Revit_Adapter/Revit_Adapter.csproj
Revit_Engine/Convert/Aliases.cs
Revit_Engine/Create/Config/RevitPullConfig.cs
Revit_Engine/Revit_Engine.csproj
Revit_oM/Config/PullGeometryConfig.cs
Revit_oM/Config/PullRepresentationConfig.cs
Revit_oM/Config/RevitPullConfig.cs
Revit_oM/Enums/DetailLevel.cs
Revit_oM/Revit_oM.csproj

Closes #681
Closes #685
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue685%2DPullRepresentations).
- `PullGeometryConfig` and `PullRepresentationConfig` have been implemented
- the above replaced `PullEdges`, `PullSurfaces` and `IncludeNonVisible` properties of `RevitPullConfig`
- Convert of Autodesk.Revit.DB.Mesh to BHoM has been implemented
This PR will break all existing scripts that used `RevitPullConfig`. I am unhappy about that, but could not think of versioning for a type that lost its `bool` properties in favour of newly implemented types.
To finish with a positive, the …

Pull of mesh representations implemented

---

Engine_Revit_UI/Query/ElementIds/ElementIdsByDBType.cs
Engine_Revit_UI/Query/Faces.cs
Engine_Revit_UI/Query/GeometryPrimitives.cs
Revit_Engine/Query/Edges.cs

Closes #432
Closes #712
Closes #713
[#432](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue432%2DQueryEdges&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
[#712](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue712%2DDBTypeCrash&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
[#713](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue713%2 …

Minor bugs fixed

---

Engine_Revit_UI/Compute/Warnings.cs
Engine_Revit_UI/Convert/Geometry/FromRevit/Curve.cs

Closes #719
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue719%2DEllipseBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
#719 states that it is a conversion bug - apparently, the conversion method is correct (it takes out as much as it can), the problem is error being raised instead of a warning. This has been fixed by this PR, further work can possibly be done as a part of https://github.com/BHoM/Revit_Toolkit/issues/445 (conversion of 2 Revit half-circles <=> 1 BHoM circle, same for ellypses).

Ellipse conversion error changed to a sensible warning

---

Engine_Revit_UI/Query/RevitTypes.cs

Closes #600
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue600%2DSupportRevitTypesWithDictionary&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - open an empty Revit doc and look up the time of an empty run (please remember the 1st run is not representative due to Revit Listener startup). On this branch it should be ~20% faster than on master.
Any column can be modelled in Revit and pulled to check if the functionality itself is still valid.

RevitTypes method supported with a private dictionary to avoid Reflection overhead

---

Revit_Core_Engine/Modify/RemoveDuplicateAnalyticalElements.cs
Revit_Core_Engine/Query/ElementIds/ElementIdsByBHoMType.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #739
[Model](https://burohappold.sharepoint.com/sites/Direction/designtechnology/Script%20Library/Forms/AllItems.aspx?csf=1&web=1&e=NiBGLn&cid=c7288618%2Ddbe3%2D46c6%2Dbdac%2D240283593d9d&RootFolder=%2Fsites%2FDirection%2Fdesigntechnology%2FScript%20Library%2F00339%5FBEnv%20Model%20Laundry%20Workflows%2F03%20Test%2FKHN&FolderCTID=0x012000877674B0FB94234BB2F1C82F2331EE6F) and [script](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue739%2DDuplicateBEnvPull&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

Pull of BEnv elements stopped from returning duplicate elements

---

Revit_Core_Adapter/Revit_Core_Adapter.csproj

Closes #748
Not needed, actions to take:
- go to _%appdata%\Autodesk\Revit\Addins\20XX_ and delete _BHoM_20XX.Addin_ file
- go to _C:\ProgramData\BHoM\Assemblies_ and delete _Revit_Core_Adapter_20XX.dll_ and _Revit_Core_Engine_20XX.dll_ files
- Rebuild Revit_Toolkit on _Debug20XX_ config and see if the files are back

Copying of .addin file fixed

---

Revit_Core_Engine/Query/FramingElementProperty.cs

Closes #756
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue756%2DCopyParametersToProperty&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
With the current approach the parameters of Revit element type will be copied over to both to BHoM `Property` and `Profile`. Although a bit confusing, this is best I could come up with (please see #756).
@rwemay @IsakNaslundBh FYI

Type parameters get copied over to Physical.IFramingElement.Property on pull

---

Revit_Core_Engine/Query/AdjustedLocationCurve.cs

Closes #763
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue763%2DPushNurbsBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

Nurbs-based framing stopped from crashing on push

---

Revit_Core_Engine/Modify/NormalizeAngleDomain.cs
Revit_Core_Engine/Modify/SetLocation.cs
Revit_Core_Engine/Modify/SetParameter.cs
Revit_Core_Engine/Query/OrientationAngle.cs

Closes #765
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue765%2DPushSlantedColumnRotationBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

Cross section rotation limited to the range accepted by Revit (-360 to +360 deg.)

---

Revit_Engine/Modify/SetRevitParameter.cs

Closes #759
Closes #766
[#759](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue759%2DSetRevitParametersBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
[#766](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue766%2DSetRevitParameterUpstreamBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- `SetRevitParameter` method has been added to handle single parameter assignment
- bug causing the objects being modified upstream on SetRevitParameter has been fixed
This PR to some extent may …

SetRevitParameters issues resolved

---

Revit_Core_Engine/Convert/Revit/FromRevit/Parameter.cs
Revit_Core_Engine/Modify/CopyParameters.cs

Closes #755
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue755%2DAllParametersBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

All type parameters stopped from being copied over to the BHoM objects on pull with type parameter mapping

---

Revit_Core_Engine/Query/GeometryPrimitives.cs

Closes #778
On [SharePoint](http://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FRevit_Toolkit%2FRevit_Toolkit-Issue778-ViewSpecificGeometry&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - simply open the doc and go to the only view in it.

Pulling of geometry enabled for DetailItems

---

Revit_Core_Engine/Modify/CopyParameters.cs

Closes #786
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue786%2DPullHiddenParams)

Pulling hidden parameters enabled when pulled Revit element does not expose any public ones

---

Revit_Core_Engine/Modify/SetLocation.cs
Revit_Core_Engine/Modify/SetType.cs

Closes #781
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue781%2DUpdateWarnings&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - open an empty document and run the script.

Irrelevant warnings and errors stopped from being thrown on update

---

Revit_Engine/Query/GetRevitParameterValue.cs

Closes #789 
Closes #790 
The GetRevitParamValue method can now get identifier and type parameters from objects pulled from Revit, which is a key feature to allow for downstream workflows.
[RevitGetParamValueTest.zip](https://github.com/BHoM/Revit_Toolkit/files/4881605/RevitGetParamValueTest.zip)

Added ability to get identifier and type params using GetRevitParamValue

---

Revit_Core_Engine/Convert/Architecture/FromRevit/Room.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Door.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Window.cs

Closes #794
Not needed, that should not change any functionality.
That issue has been investigated by @FraserGreenroyd in https://github.com/BHoM/Revit_Toolkit/issues/794, so should be safe to merge straight away as long as the discussion in the issue is still valid.

OriginContext fragment removed from non-BEnv converts from Revit

---

Revit_Core_Engine/Query/CeilingPattern.cs

Closes #801
Not possible to test from UI level actually - the line changed in this PR is never reached as it always hits `else` in the statement below:
https://github.com/BHoM/Revit_Toolkit/blob/e6613da7f5d89d2b1171d72d27abc008060988dc/Revit_Core_Engine/Query/CeilingPattern.cs#L64-L74
So the change is actually purely cosmetical and replaces a legacy `PlanarSurfaceDictionary` method with the currently supported one, `PanelSurfaces`.
To test the general functionality one can use the script from [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue801%2DRefactorCeilingPatterns&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) in …

PlanarSurfaceDictionary method replaced with PanelSurfaces in CeilingPattern query

---

Revit_Core_Engine/Convert/Structure/FromRevit/SurfaceProperty.cs

Closes #783
Script on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue783%2DHandleCurtainPanelTypes&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - the easiest way to test is to run it on an empty model (any model has a curtain wall type).
- #783 fixed
- `SurfacePropertyFromRevit` method cleaned up

SurfacePropertyFromRevit fixed not to crash on Revit panel types without any layers

---

Revit_Core_Engine/Convert/Physical/ToRevit/Floor.cs
Revit_Core_Engine/Query/LevelAbove.cs
Revit_Core_Engine/Query/LevelBelow.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #421 
Closes #429
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue421%2C429%2DPushFloorBugs&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - can be run in an empty model.
- Handling of openings on BHoM => Revit convert fixed
- BHoM => Revit convert of sloped floors enabled

BHoM => Revit floor convert bugs fixed

---

Revit_Core_Engine/Query/CeilingPattern.cs

Closes #813
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue813%2DCeilingPatternError&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

Ceiling pattern query stopped from throwing red error when there is no pattern on Revit ceiling

---

Revit_Core_Engine/Convert/Geometry/ToRevit/Curve.cs
Revit_Core_Engine/Convert/Geometry/ToRevit/CurveList.cs
Revit_Engine/Create/Elements/ModelInstance.cs
Revit_Engine/Query/CategoryName.cs

Closes #807
Closes #808
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue808%2DCurveConvertBugs&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - can be run on an empty Revit file.
- pushing of Model Curves using `ModelInstance` reenabled
- BHoM => Revit curve convert bugs fixed for 2-noded `Polyline`, single-segment `PolyCurve` and `Ellipse`
- handling of Nurbs curves on Push slightly improved (could not get any better due to Revit limiations)

Curve push and convert bugs fixed

---

Revit_Core_Engine/Query/AdjustedLocationCurve.cs
Revit_Core_Engine/Query/LocationCurve.cs
Revit_Core_Engine/Query/OrientationAngle.cs

Closes #489
Closes #775
[#489](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue489%2DNoLocationWarning&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
[#775](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue775%2DFramingExtension&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- Revit => BHoM convert of steel framing fixed to take into account _Extension_ parameters
- Revit => BHoM convert of unrecognized framing fixed not to crash but raise appropriate warnings about lack of …

Minor BHoM => Revit framing convert bugs fixed

---

Revit_Core_Engine/Compute/Errors.cs
Revit_Core_Engine/Compute/Warnings.cs
Revit_Core_Engine/Convert/ToRevit.cs

Closes #815
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue815%2DThrowErrorOnConvertFailure&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - can be tested on any Revit file.

BHoM => Revit conversion failure warning changed to error

---

Revit_Core_Adapter/CRUD/Read.cs

Closes #700
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue700%2DKeepSelectionAfterPull&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

Pull fixed not to unselect Revit elements in the process

---

Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #823
Not needed - simply build Revit_Toolkit on _Debug_ solution config and see whether _Revit_Core_Engine.dll_ file appears in _C:\ProgramData\BHoM\Assemblies_ folder.

Versionless Revit_Core_Engine stopped from getting copied over to BHoM\Assemblies on Debug and Release config

---

Revit_Core_Engine/Convert/Physical/ToRevit/Wall.cs

Closes #831
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue831%2DWallElevationBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- bug setting wrong elevation to newly created walls fixed
This PR is quite urgent as it concerns one of the core Revit_Toolkit functionalities.

Bug setting wrong elevation to newly created walls fixed

---

Revit_Core_Engine/Convert/Structure/FromRevit/Panels.cs
Revit_Core_Engine/Query/AnalyticalOutlines.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #837
Not really needed (simple renaming), but one can run try pulling structural panels from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2F%5FMacro%2FPull%2FStructure&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
Both this PR and #828 modify same .csproj file, but they can merge into each other so no conflict should occur.

BH.Revit.Engine.Core.Query.Outlines renamed to AnalyticalOutlines

---

Revit_Core_Engine/Convert/Structure/FromRevit/Profile.cs
Revit_Core_Engine/Query/LookupParameter.cs
Revit_Core_Engine/Query/SectionShape.cs

Closes #848
Closes #849
#848 on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2fsites%2fBHoM%2fInstallers%2fScripts%2fBuroHappold%5fBHoM%5fv3%2e3%2f0001%5fRevit%5fToolkit%2fPull&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302):
- _BuroHappold_BHoM_v3.3.beta_PullColumnProfiles_ for columns
- _BuroHappold_BHoM_v3.3.beta_PullFramingProfiles_ for framing
**Important:** to make the GH script work fine, Rhino document tolerance should be set to 1e-6 (usually 1e-3 by default).
To select top row of supported types, one can use a predefined selection set named _1st row_:
#849 can be tested using the 2nd file from the above, taking one of the light gauge profiles, e.g. the one under ID 1388030.
- Name matching of profile dimensions …

Profile extraction bugs fixed

---

Revit_Core_Engine/Convert/Geometry/ToRevit/Curve.cs
Revit_Core_Engine/Convert/Physical/ToRevit/Floor.cs
Revit_Core_Engine/Convert/Physical/ToRevit/RoofBase.cs
Revit_Core_Engine/Convert/Physical/ToRevit/Wall.cs

Closes #852
Check if the existing Revit elements overlap with the pushed ones.
- issue-specific test file [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue852%2DPanelOffsetBugs&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - select an element, pull it and push back, getting rid of the red GH group should be possible after fix (see description inside script)
- macro tests: best to run _BuroHappold_BHoM_v3.3.beta_CreatePanelLocation.gh_ script from [here](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2fsites%2fBHoM%2fInstallers%2fScripts%2fBuroHappold%5fBHoM%5fv3%2e3%2f0001%5fRevit%5fTool …

Floor, wall and roof offset issues fixed

---

Revit_Core_Engine/Convert/Geometry/ToRevit/Grid.cs
Revit_Core_Engine/Convert/Geometry/ToRevit/Level.cs

Closes #854
_BuroHappold_BHoM_v3.3.beta_CreateGridsLevels.gh_ with _BuroHappold_BHoM_v3.3.beta_EmptyFile.rvt_, both available [here](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2fsites%2fBHoM%2fInstallers%2fScripts%2fBuroHappold%5fBHoM%5fv3%2e3%2f0001%5fRevit%5fToolkit%2fPush&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302) - simply push standard levels first, then try two pushes from red groups.
No test for grid convert as the only implemented change is null check moved up to avoid potential crashes (obvious and not harmful).
- BHoM => Revit level convert fixed not to overwrite parameters without notice nor create duplicate levels on Push
Sorry for last minute bugfix PR - full-on testing mode 🤣

Level convert fixed not to overwrite parameters without notice nor create duplicate levels on Push

---

Revit_Core_Adapter/RevitListenerAdapter.cs
Revit_Engine/Convert/Aliases.cs

Closes #885 
Removing reference to AdapterNameId being removed in https://github.com/BHoM/BHoM_Adapter/pull/263

Remove reference to AdapterIdName in the constructor

---

Revit_Core_Engine/Convert/Structure/FromRevit/Bars.cs
Revit_Core_Engine/Query/FramingElementProperty.cs

Closes #882
Closes #883
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue882%2C883%2DPullFramingIssues&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- pull of material-specific sections without material assigned fixed to return material-specific BHoM `ISectionProperty`
- pull of bars fixed to keep the default material of `SectionProperty` loaded from library in case of failed material convert
This PR should not overlap with any of the currently open PRs.

Pull framing issues fixed

---

Revit_Engine/Create/Elements/Sheet.cs
Revit_Engine/Create/Elements/ViewPlan.cs

Closes #892
Script using the methods created before input renaming are uploaded [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2Dissue892%2DAddPreviousInputNamesAttributes&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - if they open with all wires connected, the test is passed.
- `PreviousInputNamesAttribute`s added to `Sheet` and `ViewPlan` to enable versioning of their input names

PreviousInputNamesAttributes added to Sheet and ViewPlan

---

Revit_Core_Engine/Convert/Environment/FromRevit/Duct.cs
Revit_Core_Engine/Convert/Environment/FromRevit/Pipe.cs
Revit_Core_Engine/Convert/Environment/FromRevit/Wire.cs
Revit_Core_Engine/Query/DuctSectionProfile.cs
Revit_Core_Engine/Query/DuctSectionProperty.cs
Revit_Core_Engine/Query/PipeSectionProperty.cs

https://github.com/BHoM/BHoM/pull/1069
https://github.com/BHoM/BHoM_Engine/pull/2133
Closes #897 
[Here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue897-MEP%20Converts%20Update%20Namespaces?csf=1&web=1&e=HrqIEn)
- Removing MEP.Node dependency within the convert code as this object class has been removed. Current solution requires `BH.oM.Geometry.Point`
- Sync all namespace changes
- Fix Wire convert

Update namespaces for MEP converts and align to oM changes

---

Revit_Core_Engine/Convert/Geometry/ToRevit/CurveList.cs
Revit_Core_Engine/Convert/Structure/FromRevit/Bars.cs
Revit_Engine/Modify/AddParameterLinks.cs
Revit_Engine/Modify/AddParameterMaps.cs
Revit_Engine/Modify/Append.cs
Revit_Engine/Modify/Move.cs
Revit_Engine/Modify/RemoveIdentifiers.cs
Revit_Engine/Modify/RemoveParameterLinks.cs
Revit_Engine/Modify/RemoveParameterMaps.cs
Revit_Engine/Modify/SetRevitParameter.cs
Revit_Engine/Modify/SetTag.cs

Closes #899
A few tests proving that the replaced and replacing methods work similarly is uploaded [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue899%2DReplaceGetShallowClone&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
For the more concerned, macro tests are available [here](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2fsites%2fBHoM%2fInstallers%2fScripts%2fBuroHappold%5fBHoM%5fv3%2e3%2f0001%5fRevit%5fToolkit&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302).
- calls to `GetShallowClone` replaced with `ShallowClone`
- calls to `Clone` replaced with `DeepClone`

Calls to GetShallowClone replaced with ShallowClone and Clone to DeepClone

---

.gitignore
Revit_Core_Engine/Convert/Environment/FromRevit/CableTray.cs
Revit_Core_Engine/Convert/Environment/FromRevit/Duct.cs
Revit_Core_Engine/Convert/FromRevit.cs
Revit_Core_Engine/Query/CableTraySectionProfile.cs
Revit_Core_Engine/Query/CableTraySectionProperty.cs
Revit_Core_Engine/Query/LocationCurve.cs
Revit_Core_Engine/Query/OrientationAngle.cs
Revit_Core_Engine/Query/Profile.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #859
Ignores BHoM/MEP_oM#1034
Initial convert FromRevit created for `CableTray` objects, that bypasses fittings to query its connectors to allow its line creation without gaps at fittings. This behavior has been replicated for `Duct` and `Pipe`.
An important observation is that pulling these objects may not result into a single element anymore, but a list of elements(e.g. if a cable tray has cable trays connected to it without fittings, or when there is a chain of fittings connected)
Test files [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue859-AddedConvertFromRevitForCableTrays?csf=1&web=1&e=Z4MkTp).
Added `Revit_Core_Engine.Convert.Environment.FromRevit.CableTray`
Added …

Added convert FromRevit for CableTray object

---

Revit_Core_Engine/Convert/Structure/FromRevit/Profile.cs

Closes #903
_PullFramingProfiles.rvt_ and _PullFramingProfiles.gh_ from [here](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2fsites%2fBHoM%2fInstallers%2fScripts%2fBuroHappold%5fBHoM%5fv3%2e3%2f0001%5fRevit%5fToolkit%2fPull&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302) should work - try pulling one of the non-standard profiles, e.g. ASB.
- creation of FreeFormProfile changed from constructor to Create method

Creation of FreeFormProfile changed from constructor to Create method

---

Revit_Core_Adapter/Listener/RevitListener.cs

Closes #908
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue908%2DMethodLoadWarnings&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - activate the adapter, then activate Pull in GH and check the warnings - there should be none.
- loading of BHoM methods forced to happen on startup to avoid warnings pop up on the 1st call of `RunExtensionMethod`

BHoM method loading made more eager

---

Revit_Core_Adapter/CRUD/Read.cs
Revit_Core_Adapter/Revit_Core_Adapter.csproj
Revit_Core_Engine/Modify/CopyParameters.cs
Revit_Core_Engine/Query/ElementIds/ElementIdsOfMemberElements.cs
Revit_Core_Engine/Query/Identifiers.cs
Revit_Core_Engine/Query/OpeningSurface.cs
Revit_Engine/Create/Config/RevitPullConfig.cs
Revit_oM/Config/RevitPullConfig.cs
Revit_oM/Parameters/RevitIdentifiers.cs

Closes #720 
Nested elements are now pulled when pulling from Revit if the pull config option for IncludeNestedElements=True. Default behavior is currently to include nested elements; this can be changed in the future if default nested element pulls prove too heavy, although initial benchmarking indicates minimal extra overhead for most families with nested elements.
[Revit and GH Test Files](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-%23720-NestedElements?csf=1&web=1&e=kF7kkq)
This PR includes implementation for nested instances in windows, which require unique methods due to how window geometry is calculated in revit. Most element types do not require this workaround, but some element types may going forward. …

Pulling nested elements implemented

---

Revit_Core_Engine/Convert/Environment/FromRevit/CableTray.cs
Revit_Core_Engine/Convert/Environment/FromRevit/Duct.cs
Revit_Core_Engine/Convert/Environment/FromRevit/Pipe.cs
Revit_Core_Engine/Query/LocationCurve.cs

Closes #911 
Adds the proper information to the `ConnectionProperty` to the `MEPCurve` converts. At the moment only `CableTray` is using the feature due to the lack of the property in `Duct` and `Pipe` objects.
Only the properties `IsStartConnected` and `IsEndConnected` have been assigned, the properties about the connection point have been ignored as they are irrelevant in this object and overall redundant.
Link [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue911-IncludedMEPCurveConnectorInformation?csf=1&web=1&e=5Bjkit). Check is visual, in the GH script I've separated a few cases to check and the values expected.
Modified `BH.Revit.Engine.Core.Convert.CableTrayFromRevit`
Modified …

Included MEPCurve ConnectionProperty Information

---

Revit_Core_Engine/Query/CableTraySectionProperty.cs

https://github.com/BHoM/BHoM/pull/1114
Closes #920 
[Test Files](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue920-CableTraySectionPropertyMaterial?csf=1&web=1&e=30e9ai)

Removal of CableTrayMaterial to match oM changes

---

Revit_Core_Engine/Query/CeilingPattern.cs

Closes #896
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue896%2DCeilingTiles&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - feel free to crack it further.
- ceiling pattern query refined to take rotation and local shift into account
If you look at the code, it makes no sense. Why would you create two dimensions, move them by random unit vector, then query their centers, rotate them, combine the two and rotate back? I do not know either, but that is the only way Revit allows extracting the information about the local ceiling pattern. BECAUSE WHY NOT, because they have monopoly, because it is 20 years of legacy Jenga …

Ceiling pattern bugs fixed

---

Revit_Core_Adapter/Listener/Forms/UpdatePortsForm.Designer.cs
Revit_oM/Elements/Sheet.cs
Revit_oM/Elements/ViewPlan.cs

Closes #930
Closes #934
Not needed:
- #930: run Revit, click Activate => Update Ports and compare the labels with `ConnectionSettings` property names
- #934: look up the code changes
- port naming unified across Revit and UI
- descriptions updated to `Sheet` and `ViewPlan` types

Port naming unified across Revit and UI and descriptions updated

---

Revit_Core_Engine/Compute/Errors.cs
Revit_Core_Engine/Compute/Warnings.cs
Revit_Core_Engine/Create/FamilyInstance.cs
Revit_Core_Engine/Modify/SetLocation.cs
Revit_Core_Engine/Modify/Update.cs
Revit_Core_Engine/Query/IsInside.cs
Revit_Core_Engine/Query/IsOnFace.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #931
_PushInstances.rvt_ and _PushInstances.gh_ from [this folder](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPush&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - I did my best to set up the tests in a granular, understandable way.
- update of IInstances improved to handle orientation and hosts
- minor refinements made to `Create.FamilyInstance` methods to fix the bugs caught when preparing the test scripts
@michaelhoehn @enarhi @tiagogrossi @AndreBalasian I believe it might be worth for you to have a look at `Create.FamilyInstance` methods, which is my attempt to tame one of the prime evils of Revit, family instance creation - I tried to …

Update of IInstances improved to handle orientation and hosts

---

Revit_Core_Engine/Query/LocationCurve.cs

Closes #937
_PullPipes_, _PullRectangularDucts_ and _PullRoundDucts_ from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
@tiagogrossi I have introduced the fix only to pipes and ducts, leaving cable trays untouched - taken you have tested them on more thoroughly.

MEP element location curve query fixed

---

Revit_Core_Engine/Convert/Physical/FromRevit/Door.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Window.cs
Revit_Core_Engine/Query/OpeningSurface.cs

Closes #960
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%23960%2DOpeningSurfaceBugVol2&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)- both pull of a wall with corrupted opening as well as the opening itself are tested in order to show how the warnings are managed.
- opening surface edge case bug fixed

Opening surface edge case bug fixed

---

Revit_Core_Engine/Compute/Activate.cs
Revit_Core_Engine/Query/ElementType.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #957
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%23957%2DActivateFamilySymbol&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
- Added mechanism to ensure the family type is activated before being used

Added mechanism to ensure the family type is activated before being used

---

Revit_Engine/Create/Requests/FilterTypesOfFamily.cs
Revit_Engine/Revit_Engine.csproj

Closes #969
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%23969%2DFilterTypesOfFamily&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
- removal of FilterTypesOfFamily reverted
The code should work fine as it got copy-pasted from the [last moment when it was present in the code base](https://github.com/BHoM/Revit_Toolkit/commit/7c1d77c385eed89205526ec13a0dd017c0ff7a47).

Removal of FilterTypesOfFamily reverted

---

Revit_Core_Adapter/CRUD/Delete.cs
Revit_Core_Adapter/CRUD/Read.cs
Revit_Core_Adapter/Revit_Core_Adapter.csproj
Revit_Core_Engine/Compute/SplitRequestTreeByLinks.cs
Revit_Core_Engine/Compute/Warnings.cs
Revit_Core_Engine/Convert/Environment/FromRevit/EnergyAnalysisModel.cs
Revit_Core_Engine/Convert/FromRevit.cs
Revit_Core_Engine/Query/CeilingPattern.cs
Revit_Core_Engine/Query/Curves.cs
Revit_Core_Engine/Query/ElementIds/ElementIds.cs
Revit_Core_Engine/Query/Faces.cs
Revit_Core_Engine/Query/GeometryPrimitives.cs
Revit_Core_Engine/Query/MeshedGeometry.cs
Revit_Core_Engine/Query/RenderMeshes.cs
Revit_Core_Engine/Query/Solids.cs
Revit_Core_Engine/Revit_Core_Engine.csproj
Revit_oM/Requests/FilterByLink.cs
Revit_oM/Revit_oM.csproj

Closes #396
- [issue-specific test file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%23396%2DPullFromLinks&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- [standard test files for requests extended to links](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FRequests%2FLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
**IMPORTANT:** Please see the additional comments for more information.
- `LinkRequest` object introduced
- handling of the above object implemented, enabling pulling from links
First of all, apologies for the …

Pull from links partially enabled

---

Revit_Core_Engine/Query/Identifiers.cs
Revit_Engine/Query/HostId.cs
Revit_Engine/Query/LinkPath.cs
Revit_Engine/Query/Workset.cs
Revit_Engine/Revit_Engine.csproj
Revit_oM/Parameters/RevitIdentifiers.cs

Not direct dependency, but versioning needs to be run on https://github.com/BHoM/Versioning_Toolkit/pull/141.
Closes #945
Closes #963
Closes #973
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%23977%2DNewIdentifiers&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - please note that full functionality requires rebuilding Versioning_Toolkit on https://github.com/BHoM/Versioning_Toolkit/pull/141.
- `Workset`, `HostId` and `LinkPath` properties added to `RevitIdentifiers` fragment
- `Query` methods extracting the above information from a `BHoMObject` added

New Revit identifiers added

---

Revit_Adapter/RevitAdapter.cs

Closes #979
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%23979%2DRevitEvents&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - the content of the warnings on Pull does not matter, it is all about recording them at all.
- logging of events coming from Revit fixed

Logging of events coming from Revit fixed

---

Revit_Core_Engine/Convert/Structure/FromRevit/Profile.cs
Revit_Core_Engine/Query/FramingElementProperty.cs

Closes #972
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%23985%2DProfilesComeOutFlipped&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- `FreeFormProfiles` from framing stopped from coming out flipped on Pull
- account made for mirroring of framing on Pull
This closes #972, but #984 has been raised as a follow-up to cover the tricky bits that could not be resolved using any conventional approach.

Revit_Toolkit: FreeFormProfiles stopped from being flipped and account made for mirroring of framing

---

Revit_Core_Engine/Convert/Physical/ToRevit/Rebar.cs
Revit_Core_Engine/Convert/ToRevit.cs
Revit_Core_Engine/Query/ElementType.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #955 
Adding simple `ToRevit` convert for `IReinforcementBar` physical objects and inheritors.
[SharePoint](https://burohappold.sharepoint.com/:f:/s/BHoM/EtVrncjlGQdPozEOFd1ff5EBdXaTDelq9rWUimR1V0uQWg?e=l4ZaaJ)
- Adding `ToRevitRebar` methods for `IReinforcementBar` interface to the `Revit_Core_Engine` project.
See [comment below](https://github.com/BHoM/Revit_Toolkit/pull/956#issuecomment-777579118).

Adding rebar ToRevit convert method

---

Revit_Core_Engine/Query/LinkPanelFaces.cs
Revit_Core_Engine/Query/OpeningSurface.cs
Revit_Core_Engine/Query/PanelSurfaces.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

https://github.com/BHoM/BHoM_Engine/pull/2398
Closes #975
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull%2FFromLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4), both scripts mentioned below to be run with _FromLink_PullPanelLocation.rvt_.
**PULL PHYSICAL**
_FromLink_PullWallFloorRoofLocation.gh_
- elements marked as 1 in the snip below fail because the panel is entirely split by the openings - that is something that I could not make any better without opening a transaction (which is not allowed on links 🙄)
- elements marked as 2 get converted to Physical objects with location as `PolySurface`, which fails on transform due to …

Pull of panels from links fixed to possible extent

---

Revit_Core_Engine/Query/OpeningSurface.cs

Closes #997
[Standard IInstance pull test](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - open _PullIInstances.rvt_ and _PullIInstances.gh_, try pulling the following:
- curve based no host
- curve based face hosted
- `OpeningSurface` method stopped from crashing on null `surfaces` variable

OpeningSurface stopped from crashing on null

---

Revit_Core_Engine/Compute/PrepareForLinkDimensioning.cs
Revit_Core_Engine/Query/CeilingPattern.cs
Revit_Core_Engine/Query/LinkInstance.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Not a direct dependency, but https://github.com/BHoM/BHoM_Engine/pull/2407 is required to avoid stack overflow on pull of the ceiling patterns.
Closes #974
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%23996%2DPullCeilingPatternFromLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - run *FromLink_#974-PullCeilingPatternFromLink.rvt* in combination with *#974-PullCeilingPatternFromLink.gh* and visually inspect the outputs.
- Pull ceiling patterns from links fixed
Please do not even bother to review `PrepareForLinkDimensioning` - it is yet another chapter of [reference and dimensioning …

Pull ceiling patterns from links fixed

---

Revit_Core_Engine/Query/OpeningSurface.cs

https://github.com/BHoM/BHoM_Engine/pull/2416
Closes #1001
- problem-specific files: *#1001-TransformPolySurfaceBug.gh* from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%231001%2DTransformPolySurfaceBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4), to be tested with _FromLink_PullPanelLocation.rvt_ from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull%2FFromLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- general test files: _FromLink_PullWallFloorRoofLocation.gh_ with _FromLink_PullPanelLocation.rvt_ …

BH.oM.Physical.Elements.ISurfaces stopped from failing to transform when their Location is not PlanarSurface

---

Revit_Core_Adapter/CRUD/Read.cs
Revit_Core_Engine/Compute/SplitRequestTreeByLinks.cs
Revit_Core_Engine/Query/ElementIds/ElementIds.cs
Revit_Core_Engine/Query/ElementIds/ElementIdsByVisibleInView.cs
Revit_Core_Engine/Query/ElementIds/ElementIdsOfActiveView.cs

Closes #999
_Link_StandardRequests_ on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FRequests%2FLink&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - no need to go through the whole test file, only orange groups should be relevant.
- Querying link documents for ElementIds made more robust and errors made more informative

Querying link documents for ElementIds made more robust and errors made more informative

---

Revit_Core_Engine/Convert/Facade/FromRevit/CurtainWall.cs
Revit_Core_Engine/Convert/Facade/FromRevit/FrameEdge.cs
Revit_Core_Engine/Convert/Facade/FromRevit/Opening.cs
Revit_Core_Engine/Convert/Facade/FromRevit/Panel.cs
Revit_Core_Engine/Convert/FromRevit.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Wall.cs
Revit_Core_Engine/Query/BuiltInCategories.cs
Revit_Core_Engine/Revit_Core_Engine.csproj
Revit_Engine/Query/Discipline.cs
Revit_oM/Enums/Discipline.cs

Please note this PR addresses phase one of #890 only, covering the initial setup of additional files, the facade enum, and the required convert switch changes to allow for the pull capability pr to follow.  This has been split into two separate PR's as phase one (this PR) is likely to cause merge issues if left as part of the larger effort. Review of this PR should cover maintenance of existing Revit_Toolkit functionality, as well as proper framework for future Facade Discipline pulls as tested in the test script included when pulling `Windows`, `CurtainWalls`, `Walls`, `Doors`, and `Mullions` (all of which should currently return not implemented errors).
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/%23890-FacadeElementPulls …

Initial Setup for Facade Discipline Additions

---

Revit_Core_Engine/Query/ElementType.cs

Closes #1039
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FFamilyLibrary) - on `master` it simply does not work, while on this branch should 🙈 
@enarhi @tiagogrossi I would be thankful for the review of one of you - this is pretty urgent as the bug should be removed before the Beta release. Thanks!

FamilyLibrary re-enabled on ElementType query

---

Revit_Core_Engine/Convert/MEP/FromRevit/CableTray.cs
Revit_Core_Engine/Query/LocationCurve.cs

[BHoM/BHoM#1248](https://github.com/BHoM/BHoM/pull/1248)
Closes #1036
Simplifies the converts `FromRevit` for the linear MEP objects (cable tray, duct and pipe).
Test files `PullCableTrays.rvt` and `PullCableTrays.gh` are [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&sortField=LinkFilename&isAscending=true&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull)
Modified `BH.Revit.Engine.Core.Convert.CableTrayFromRevit`
Modified `BH.Revit.Engine.Core.Query.LocationCurveMEP`
A follow up PR will address the addition of the MEP fitting object convert. This PR has simplified the converts of linear objects to not …

Revit_Core_Engine: Fix MEP linear objects converts

---

Revit_Core_Engine/Create/View/View3D.cs

Closes #1052 
Adds an optional input field in the `Create.View3D` method that uses BoundingBoxXYZ to crop the 3D view to fit it.
Modified `BH.Revit.Engine.Core.Create.View3D`

Revit_Core_Engine: Allow custom boundingbox for isometric 3D views

---

Revit_Core_Engine/Convert/FromRevit.cs
Revit_Core_Engine/Convert/MEP/FromRevit/Fitting.cs
Revit_Core_Engine/Query/BuiltInCategories.cs
Revit_Core_Engine/Query/MEPConnectorsLocation.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #864 
Implements the pull converter for MEP fittings. Currently duct fittings, duct accessories, pipe fittings, pipe accessories and cable tray fittings categories have been bundled to convert to a ` BH.oM.MEP.System.Fittings.Fitting`. This is a generic approach that aims to enable users to start performing graph operations in these objects.
A future task is suggested to further refine these categories, by for example taking advantage of the Fitting property `FittingType`, that uses undefined value for now.
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FTool …

Revit_Core_Engine: Fitting pull converter implemented

---

Revit_Core_Engine/Convert/MEP/FromRevit/Wire.cs

Closes #1083
_PullWires_ from [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
I do not think wire converts were heavily used, so I am quite comfortable with this last minute breaking change.

Return type of wire convert aligned

---

Revit_Engine/Create/Config/RevitPullConfig.cs

Closes #1087
The origin of the issue is _PullFramingProfiles.gh_ from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
Test of another version has been added [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231088%2DCreateRevitPullConfigVersioning&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4). Since the input order changed between the versions, I am adding a screenshot from the old version too:

Create.RevitPullConfig versioned

---

Revit_Core_Engine/Convert/Revit/FromRevit/DraftingInstance.cs
Revit_Core_Engine/Query/AnalyticalOutlines.cs

Closes #1062 
Closes #1008 
(#1008 is closed primarily by the previous Tolerance parameter capabilities, as the issue can be solved with current Revit_Toolkit capabilities along with a tolerance input value on the IArea method that matches the RevitSettings.DistanceTolerance value accordingly.)
Allows for tolerance set in RevitSettings to be applied to Planar Surface creation, thereby allowing pulling closed regions such as a FilledRegion where the region is closed per Revit tolerances, but not per default BHoM tolerances.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/%231062-PlanarSurfaceTolerance?csf=1&web=1&e=kDTc7h
Test by checking with the different tolerances to confirm pull failure when tolerance value is too low, and …

Add tolerance parameter for pull with PlanarSurface and IsClosed methods

---

Revit_Core_Engine/Compute/Warnings.cs

Closes #1013
Not really needed (it is just a warning message change), but added a sample case on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231092%2DTypeNotFoundWarningMadeMoreInformative&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

ElementTypeNotFoundWarning made more informative

---

Revit_Core_Engine/Create/FamilyInstance/FamilyInstance.cs

Closes #1093
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPush&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4):
- _CreateUpdateIInstances.rvt_ + _CreateUpdateIInstances.gh_
- _PlaceFamilyInstanceOnMEPCurve.rvt_ + _PlaceFamilyInstanceOnMEPCurve.gh_

Bug in Create.FamilyInstance for one level based, non-hosted families fixed

---

Revit_Core_Engine/Compute/Warnings.cs

Closes #1013
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231092%2DTypeNotFoundWarningMadeMoreInformative&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
This is a further refinement of https://github.com/BHoM/Revit_Toolkit/pull/1092 requested by @JosefTaylor.

ElementTypeNotFoundWarning made even more informative

---

Revit_Core_Engine/Convert/Physical/ToRevit/FamilyInstance.cs

Closes #1119
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231120%2DPushBracingBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

Pushing braces based on object name matching fixed

---

Revit_Engine/Compute/RevitDiffing.cs
Revit_Engine/Query/ComparisonInclusion.cs
Revit_Engine/Query/HashString.cs
Revit_Engine/Revit_Engine.csproj
Revit_Engine/Versioning_50.json
Revit_oM/Config/RevitComparisonConfig.cs
Revit_oM/Revit_oM.csproj

https://github.com/BHoM/BHoM_Engine/pull/2699
Closes https://github.com/BHoM/Revit_Toolkit/issues/1117
See the changelog below and the description in https://github.com/BHoM/BHoM_Engine/pull/2699 and https://github.com/BHoM/BHoM/pull/1306.
**Note**: this replaces https://github.com/BHoM/Revit_Toolkit/pull/1109 due to rebase conflicts.
https://burohappold.sharepoint.com/:f:/s/BHoM/EsE5svn2eC9EsBM8PZtEOh4BzurxPs9qU6RlYsbd1b-K_g?e=mxisBC
- The new public `RevitDiffing` methods are simpler and offer multiple usage options to users
- Added a new `RevitComparisonConfig` for Revit-specific diffing options
- Implemented the `Query.ComparisonInclusion()` function that takes a `RevitParameter` input; it also uses the `RevitComparisonConfig` for revit-specific options. This …

Revit_Engine: aligments and simplifications of the RevitDiffing backend

---

Revit_Core_Adapter/AdapterActions/Pull.cs
Revit_Core_Adapter/CRUD/Delete.cs
Revit_Core_Adapter/CRUD/Read.cs
Revit_Core_Engine/Convert/FromRevit.cs
Revit_Engine/Modify/DefaultIfNull.cs
Revit_Engine/Query/Discipline.cs
Revit_Engine/Revit_Engine.csproj

Closes #1128
Chosen few files from the [standard test files](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FRevit%5FToolkit%2FPull&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) should be enough.
- return type of `IFromRevit` as well as `Read` methods changed to `List<IBHoMObject>`
- discipline ambiguity removed from `Read` method signatures (input of type `Discipline` removed from all methods taking `RevitPullConfig`)
- `Read(Document, List<ElementId>, RevitPullConfig, RevitSettings)` extracted from the wider Read(Document, IRequest, RevitPullConfig, RevitSettings) method
- minor tweaks to align with the above changes

IFromRevit method cleaned up

---

Revit_Core_Engine/Convert/Physical/ToRevit/FamilyInstance.cs

Closes #1134
Quickfix for @enarhi - hopefully able to test using your project work.

Framing elements stopped from being pushed with wrong length in case of default Start/End Extension param value not equal to zero

---

Revit_Core_Adapter/Listener/RevitListener.cs
Revit_Core_Engine/Compute/LoadSensitiveDynamoAssemblies.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #1136
Ideally run the installer from [this SP folder](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&isAscending=true&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231137%2DLoadDynamoAssemblies&sortField=LinkFilename&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b) (or compile the code) and see if you are able to run Dynamo in Revit **_on each version_**.
The problem turned to lie in the version of Python.Runtime used by Dynamo (2.5 or similar) vs recent versions loaded by BHoM (~3.7). As usual, [Autodesk is very helpful when it comes to supporting their user …

Dynamo stopped from crashing because of BHoM loading different version of assemblies on startup 

---

Revit_oM/Config/RevitComparisonConfig.cs

Closes #1138
No functional change, just a minor compliance fix. 
https://burohappold.sharepoint.com/:f:/s/BHoM/EsE5svn2eC9EsBM8PZtEOh4BzurxPs9qU6RlYsbd1b-K_g?e=cTccfB

Revit_oM: `RevitComparisonConfig` to inherit from `BaseComparisonConfig`, not `ComparisonConfig`

---

Revit_Engine/Versioning_50.json

Fixes Versioning Checks.
@alelom @pawelbaran can we be careful to ensure any rebased PRs don't change files they shouldn't be changing as part of their work please - the rebase for diffing removed the additions to `Versioning50.json` for deleted panels. Just a gentle reminder! 😸

Reimplement versioning for deleted panel create methods.

---

Revit_Core_Engine/Query/MaterialTakeoff.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Does not depend on for compilation, but done in alignment with https://github.com/BHoM/BHoM/pull/1341 and https://github.com/BHoM/BHoM_Engine/pull/2733.
Checks done in constructor migrated to engine Create method.   
Calling Create method rather than constructor straight away to ensure checks and potential error messages are raised appropriately

Calling Create method rather than constructor for MaterialComposition

---

Revit_Core_Engine/Convert/Physical/ToRevit/FamilyInstance.cs
Revit_Core_Engine/Convert/Physical/ToRevit/Floor.cs
Revit_Core_Engine/Convert/Physical/ToRevit/RoofBase.cs
Revit_Core_Engine/Convert/Physical/ToRevit/Wall.cs
Revit_Core_Engine/Convert/Revit/ToRevit/Element.cs
Revit_Core_Engine/Modify/SetType.cs
Revit_Core_Engine/Query/BuiltInCategories.cs
Revit_Core_Engine/Query/ElementType.cs

Closes #1146
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231154%2DSetTypeCleanup&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
- Revit element type search centralised for creation and update of the elements based on the BHoM objects
- informative warnings added to explain to the user what is the source of the element type information for given convert (BHoM object name vs name of its defining property like `Construction`)
- `Query.ElementType` stopped from modifying the queried Revit element types
The problem proved to be much more complex than originally stated #1146. There were 3 parallel challenges to deal with:
- element …

Element type query centralised and made more logical

---

.github/CODEOWNERS

Closes #1170
Not affecting the code.

CODEOWNERS file removed

---

Revit_Core_Engine/Convert/Architecture/FromRevit/Opening.cs
Revit_Core_Engine/Convert/Architecture/FromRevit/Room.cs
Revit_Core_Engine/Convert/Environment/FromRevit/Space.cs
Revit_Core_Engine/Convert/MEP/FromRevit/CableTray.cs
Revit_Core_Engine/Convert/MEP/FromRevit/Duct.cs
Revit_Core_Engine/Convert/MEP/FromRevit/Fitting.cs
Revit_Core_Engine/Convert/MEP/FromRevit/Pipe.cs
Revit_Core_Engine/Convert/MEP/FromRevit/Wire.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Construction.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Door.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Window.cs
Revit_Core_Engine/Convert/Revit/FromRevit/TypeFragment.cs
Revit_Core_Engine/Modify/CopySpatialElementTypeToFragment.cs
Revit_Core_Engine/Modify/CopyTypeToFragment.cs
Revit_Core_Engine/Query/Construction.cs
Revit_Core_Engine/Revit_Core_Engine.csproj
Revit_Engine/Query/GetRevitElementType.cs
Revit_oM/Misc/RevitTypeFragment.cs
Revit_oM/Revit_oM.csproj

Covers large portion of #1169
PR-specific test file on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231174%2DRevitTypeHandling&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
Builders work openings can be tested using [this script](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231127%2DOpeningConverts%2FOpenings&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b)
BEnv openings can be test using PullBEnvModel from [this …

RevitTypeFragment introduced and BHoM converts fixed to pass the type information to the output object

---

Revit_Core_Engine/Query/LookupParameter.cs

Closes #1177 
Adds new functionality in `Query.LookupParameter`, to return a parameter from element, including type, that doesn't requires a `MappingSettings`.
Modified `BH.Revit.Engine.Core.Query.LookupParameter`

Add new features to Query.LookupParameter

---

Revit_Core_Engine/Query/StringValue.cs

Tweak of StringValue method to return actual string as shown by Revit

---

Revit_Core_Engine/Modify/SetInsulation.cs

Closes #1191 
Changing `SetInsulation` return type from `void` to `InsulationLiningBase` to have better control when used in other methods.

Change SetInsulation return type

---

Revit_Core_Engine/Convert/Revit/FromRevit/Color.cs
Revit_Core_Engine/Convert/Revit/ToRevit/Color.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #1184 
Color convert added, from System.Drawing to Revit API and vice-versa.
N/A
Added `BH.Revit.Engine.Core.Convert.Color.ToRevit`
Added `BH.Revit.Engine.Core.Convert.Color.FromRevit`

Revit_Core_Engine: Add Color convert Rebased

---

Revit_oM/Config/RevitComparisonConfig.cs

Closes #1199
Invoke the RevitDiffing tests in [DiffingTests_Prototypes ](https://github.com/BHoM/DiffingTests_Prototypes). They should all pass.
- The default NumericalTolerance for RevitDiffing is now set to **`1e-6`** instead of `Double.MaxValue`. This will affect every Diffing done with RevitDiffing from now on. Comparisons on the same sets of objects done previously with RevitDiffing will return different results after this PR, if the default tolerance of was used. To replicate the same results as before, set `Double.MaxValue` manually on the NumericTolerance property of the RevitComparisonConfig before triggering the RevitDiffing.

RevitComparisonConfig.NumericTolerance overridden

---

Revit_Core_Engine/Convert/Architecture/FromRevit/Room.cs

Closes #1208
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231209%2DRoomFromRevitBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

RoomFromRevit stopped from crashing on rooms without outlines

---

Revit_Core_Engine/Query/CeilingPattern.cs

Closes #1201 
Fixed the method for extracting pattern lines of a Revit ceiling being pulled. Also, added code for looking up a painted material if the compound structure's material doesn't have a surface pattern. This is based on ceilings in Kayleigh's test file which have painted materials.
Same file Kayleigh sent us before but with one ceiling changed to the "GWB" type. The ceiling type triggered the issue, not the number of ceilings selected before the pull.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/Revit_Core_Engine-%231201-HandlePullingCeilingsWithoutValidMaterialPatterns?csf=1&web=1&e=bWOGJW
- Handled pulling ceilings where their surface patterns are painted or unavailable.

Revit_Core_Engine: Handled exceptions on obtaining ceiling pattern lines

---

Revit_Core_Engine/Query/Passes.cs

Closes #1217 
Fixed `Passes` method to work with empty parameter values correctly.
[Revit 2018 model](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BuroHappoldEngineering/BuroHappold_Revit_Toolkit/%23461-InsulationToolQA?csf=1&web=1&e=l586BA)
1. Open Insulation Tool setting window
2. Set filtering in scenario for any parameter as Not Equal or Not Contains (may be Comments)
3. Run apply method

Scenario filtering empty parameter fix

---

Revit_Core_Engine/Convert/Revit/Internal/ToSolid.cs
Revit_Core_Engine/Query/Bounds.cs
Revit_Core_Engine/Query/DoesIntersect.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #1223 
- Added `Does Intersect` method for checking the intersection between elements.
- Method `Bounds` for getting the bounding box of the element has been changed.
- Extend `ToSolid` method for bounding box elements.
[Revit 2018 models](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/%231224-DoesIntersect?csf=1&web=1&e=eJhNxD)
- `MEP Model` as a Host
- `Arch Model` as a Link
- `LinkVsLink` to check intersection between linked elements

DoesIntersect method for checking the intersection between elements

---

Revit_Core_Engine/Convert/Physical/FromRevit/Beam.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Bracing.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Column.cs
Revit_Core_Engine/Query/ElementType.cs

Closes #1239
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231240%2DNamingOfFramingElements&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

Naming of Framing elements on Push and Pull made behave more consistently

---

Revit_Core_Engine/Create/Solid.cs
Revit_Core_Engine/Query/LinkedElementsInView.cs
Revit_Core_Engine/Query/Tessellate.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #1202 
- added `LinkedElementsInView` method to get linked elements from given view
- added `Tessalate` method to convert `CuveLoop` to list of points
- extend `Solid` method to get the `Solid` from `ViewPlan`
New PR for #1231

LinkedElementsInView, CurveLoop Tessellate, View to Solid methods

---

Revit_Core_Adapter/CRUD/Read.cs
Revit_Core_Engine/Compute/CachePanelGeometry.cs
Revit_Core_Engine/Convert/Architecture/FromRevit/Ceiling.cs
Revit_Core_Engine/Convert/Environment/FromRevit/Panel.cs
Revit_Core_Engine/Convert/Facade/FromRevit/Panel.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Door.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Floor.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Roof.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Wall.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Window.cs
Revit_Core_Engine/Convert/Structure/FromRevit/Panels.cs
Revit_Core_Engine/Objects/OutlineCache.cs
Revit_Core_Engine/Objects/SurfaceCache.cs
Revit_Core_Engine/Query/CurtainPanels.cs
Revit_Core_Engine/Query/InsertsToIgnore.cs
Revit_Core_Engine/Query/IsSimilar.cs
Revit_Core_Engine/Query/OpeningSurface.cs
Revit_Core_Engine/Query/OutlineCacheKey.cs
Revit_Core_Engine/Query/PanelPlanes.cs
Revit_Core_Engine/Query/PanelSurfaces.cs
Revit_Core_Engine/Query/SurfaceCacheKey.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #1236
Closes #1237
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231238%2DPanelConvertPerformance&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
Worth testing the standard test procedure files too @vietle-bh 
- Revit => BHoM panel convert performance improved
- facade panel convert bug fixed
The proposed performance improvement is quite complex in implementation, but I will try to explain it in a few points 🙈 
**Before:**
- each panel element converted individually
- temporary transaction and document regeneration done for each element separately
**After:**
- each panel element converted individually
- before any converts …

Revit => BHoM panel convert performance improved plus minor facade panel convert bug fixed

---

Revit_Engine/Compute/RevitDiffing.cs

Closes #1246 
Improves the error message given when duplicate ids is detected. Gives further guidance to use physical elements rather than structural if structural elements are detected.
Changing the Diffing method called to one one step deeper as ids are already extracted.
(from @alelom) added a [test for this PR in DiffingTests_Prototypes](https://github.com/BHoM/DiffingTests_Prototypes/commit/4fd6beb6341649b0a350acec1f9fc8f29fd2d00a#diff-12ea9316c7af69edaf879938250d10c04a67762da06fdfc224959d42eb8e8c80). Run all tests in that solution to verify this PR.

Revit_Engine: Improve error message when diffing with duplicate elementIds

---

Revit_Core_Engine/Query/ConnectedElements.cs
Revit_Core_Engine/Query/Intersections.cs
Revit_Core_Engine/Query/LinkedElementsInView.cs
Revit_Core_Engine/Query/Shape.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #1244 
Added method to get the intersection result between curve and solid.
- added `ConnectedElements` method to get elements connected to MEP object
- added `Shape` method to get the shape of the `FamilyInstance` object

Revit_Core_Engine: Solid/Curve intersections, MEP connected elements, MEP shape queries

---

Revit_Core_Engine/Convert/Physical/ToRevit/FamilyInstance.cs
Revit_Core_Engine/Modify/SetParameter.cs
Revit_Core_Engine/Query/ParameterType.cs

Closes #1254
Closes #1255
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231257%2DPushVerticalColumn&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

Column style fixed on push of vertical columns + setting enum parameters re-enabled

---

Revit_Core_Engine/Compute/CachePanelGeometry.cs

Closes #1264
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231265%2DIrrelevantDuctError&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
@vietle-bh not sure how did this pass the Beta tests 🙈

Irrelevant error on pull of MEPCurves removed

---

Revit_Core_Engine/Compute/CreateTransformed.cs
Revit_Core_Engine/Create/FamilyInstance/FamilyInstance.cs
Revit_Core_Engine/Query/BoundsOfTransformed.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

Closes #1258 
- added `CreateTransformed` method for creating transformed bounding box
- null check added to `FamilyInstance`

Bounding Box Create Transformed method added, FamilyInstance null check added

---

Revit_Core_Engine/Objects/Active2dViewVisibilityContext.cs
Revit_Core_Engine/Objects/ActiveViewVisibilityContext.cs
Revit_Core_Engine/Query/ElementIds/ElementIds.cs
Revit_Core_Engine/Query/ElementIds/ElementIdsByVisibleInActiveView.cs
Revit_Core_Engine/Query/ElementIds/ElementIdsByVisibleInView.cs
Revit_Core_Engine/Revit_Core_Engine.csproj
Revit_oM/Requests/FilterByVisibleInActiveView.cs
Revit_oM/Requests/FilterByVisibleInView.cs
Revit_oM/Revit_oM.csproj

Closes #1261
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231262%2DLinkedElementsFromActiveView&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - try hiding the elements to validate the behaviour.
@vietle-bh @travispotterBH @michal-pekacki please have a look at `ActiveViewVisibilityContext` and its application in filtering the visible linked elements - can be helpful in other applications 👍

Mechanism for filtering linked elements visible in the active view of host document added

---

Revit_Core_Engine/Create/FamilyInstance/FamilyInstance.cs

Closes #1267 
Placing family instance on MEPCurve doesn't work for specific cases (sloped pipes). This fix changes connector location check from `IsAlmostEqual` to `DistanceTo` to avoid null connector values.

Family Instance on MEPCurve connectors fix

---

Revit_Core_Engine/Convert/Physical/ToRevit/Floor.cs

Closes #1270
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231271%2DPushOfSlabsBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - open a new project in Revit 2022 or 2023, then do the push and check whether the floors are in correct location

Bug in push of slabs to Revit 2022/23 fixed

---

Revit_Core_Engine/Convert/Geometry/FromRevit/BoundingBox.cs
Revit_Core_Engine/Query/ClosestElement.cs
Revit_Core_Engine/Revit_Core_Engine.csproj

BoundingBoxXYZ.FromRevit() added and closest element query tweaked to optionally include nested curtain elements

---

Revit_Core_Engine/Query/GeometryPrimitives.cs
Revit_Core_Engine/Query/LinkPanelFaces.cs

Closes #1280
See https://github.com/BHoM/Revit_Toolkit/issues/1280
From the two issues raised in the original issue:
Null reference was an easy fix, occurred when the solid was entirely outside of the half space, which makes perfect sense.
Generating ids error originates from an edge case where the element had its geometry defined both as instance geometry and element geometry (from what I understand, instance geometry is the geometry created based on the family definition, while the element geometry is what it actually is in the model - see [Revit API docs](https://www.revitapidocs.com/2018.2/fe25b14f-5866-ca0f-a660-c157484c3a56.htm) for more details):
- usually walls have only element geometry, for some weird reason some of them also have instance one:
...from what I understand, …

Revit_Core_Engine: pull of windows from link fixed

---

Revit_Core_Engine/Compute/GenerateProfile.cs
Revit_Core_Engine/Convert/Physical/ToRevit/Floor.cs
Revit_Core_Engine/Convert/Physical/ToRevit/RoofBase.cs
Revit_Core_Engine/Convert/Physical/ToRevit/Wall.cs
Revit_Core_Engine/Convert/Structure/FromRevit/Panels.cs
Revit_Core_Engine/Query/AnalyticalOutlines.cs

Closes #1283
Closes #1284
Closes #1286
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231285%2DMessageTweaks&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

Messaging tweaked and bug in roof push fixed

---

Revit_Core_Engine/Convert/FromRevit.cs

Closes #1290 
Revit elements with nurbs curves in their boundaries will fail to pull with the message "Outline isn't closed" message. This PR handles another error this exception then triggers.
On [SharePoint](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/Revit_Core_Engine-%231290-NullException?csf=1&web=1&e=5EAe64)
- Remove the irrelevant error message due to the same error thrown twice.

Revit_Core_Engine: Handle null exception on Nurbs curves in element boundaries

---

Revit_Core_Engine/Convert/Structure/FromRevit/Bars.cs
Revit_Core_Engine/Convert/Structure/FromRevit/Profile.cs
Revit_Core_Engine/Query/LibraryMaterial.cs

https://github.com/BHoM/BHoM_Datasets/pull/122
Aligns hardcoded paths to datasets migrated to discipline superfolder.

Align with migration of Structures datasets to subfolder

---

Revit_Core_Engine/Convert/Physical/FromRevit/MeshElement.cs
Revit_Core_Engine/Revit_Core_Engine.csproj
Revit_Engine/Compute/RevitDiffing.cs

Adds method for converting any element to MeshElement from Revit

Add method for converting MeshElement from revit

---

Revit_Core_Engine/Convert/Physical/ToRevit/FamilyInstance.cs

Closes #1308
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FRevit%5FToolkit%2F%231308%2DFramingReferenceLevelBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

Framing level on push bug fixed

---

README.md

Readme updated to include Revit 2023

---

Revit_Core_Adapter/Listener/Buttons/BHoMVersion.cs
Revit_Core_Adapter/Listener/Buttons/BHoMWebsite.cs
Revit_Core_Adapter/Listener/Buttons/BHoMWiki.cs
Revit_Core_Adapter/Listener/RevitListener.cs
Revit_Core_Adapter/Revit_Core_Adapter.csproj
dependencies.txt

Closes #1296 
- BHoM Version Button added to UI
- Website Links Updated

Add BHoM Information Version Button and Update Website Links

---

Revit_Core_Engine/Convert/Revit/ToRevit/Element.cs
Revit_Core_Engine/Convert/Revit/ToRevit/ElementType.cs
Revit_Core_Engine/Convert/Revit/ToRevit/Family.cs
Revit_Core_Engine/Convert/ToRevit.cs
Revit_Core_Engine/Query/BuiltInCategories.cs
Revit_Core_Engine/Query/BuiltInCategory.cs
Revit_Core_Engine/Query/CategoriesWithNames.cs
Revit_Core_Engine/Query/CategoryName.cs
Revit_Core_Engine/Query/ElementIds/ElementIdsByCategory.cs
Revit_Core_Engine/Query/ElementType.cs
Revit_Core_Engine/Query/Family.cs
Revit_oM/Enums/Category.cs

Closes #1226
Closes #1295
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231312%2DCategoriesAsEnum&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - open your fav model and try pulling by category chosen from dropdown. Dropdown UX improvement has been proposed in https://github.com/BHoM/Grasshopper_UI/pull/677 and https://github.com/BHoM/BHoM_UI/pull/450.
- `BH.oM.Revit.Enums.Category` added with all Revit categories along with human-readable labels in attributes
- category matching mechanism has been refined in a way that if a category is correctly added to the above enum, it will both appear in the UI dropdown as well as become …

Enum reflecting Revit categories added and category matching mechanism refactored

---

Revit_Core_Engine/Convert/Physical/FromRevit/MeshElement.cs

Closes #1319
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231321%2DMeshElementConvertBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

Convert from Revit to MeshElement stopped from crashing in case of invalid Revit geometry

---

Revit_Core_Engine/Convert/Structure/FromRevit/Bars.cs

Closes #1323 
Added a check on location curve type to prevent a null reference.
Requires Revit 2022.
[SharePoint folder](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/%231323-FixNullExceptionOnPullingNurbsBars?csf=1&web=1&e=miI65E)
Pull any Revit beam that is based on a Nurbs curve. Any ID below will do:
1208663, 1208973, 1209221, 1209288, 1209467, 1209792, 1209794, 1209824, 1209826, 1209828, 1209830, 1209832, 1209834, 1209836, 1209876, 1209878, 1209880, 1209882, 1209884, 1209886, 1209888, 1209930, 1209932, 1209934, 1209936, 1209938, 1209940, 1209942, 1209982, 1209984, 1209986, 1209988, 1209990, 1209992, 1209994, 1210036, 1210038, 1210040, 1210042, 1210044, 1210046, 1210048, 1211097, 1211099, 1211101, 1211103, 1211105, …

Fix null exception on pulling Nurbs bars

---

Revit_Core_Engine/Objects/SpecTypeId.cs
Revit_Core_Engine/Objects/UnitTypeId.cs
Revit_Core_Engine/Query/UnitTypeByPropertyName.cs

Irrelevant unit type warnings suppressed

---

Revit_Engine/Compute/RevitDiffing.cs

Closes #1333
Fixes some mistakes in the assignment of the properties to the DiffingConfig during the RevitDiffing.  
This removes some side-effects in edge cases like when using the `RevitComparisonConfig.ParameterNumericTolerances` feature.
Run the tests in DiffingTests prototypes. All must pass. The relevant ones are the ones linked in https://github.com/BHoM/DiffingTests_Prototypes/issues/10: in the `RevitDiffingTests` project, look for  `PropertyNumericTolerances_Equal` and `PropertyNumericTolerances_Different` (in the test class `RevitObjectDifferencesTests`).
- Fixes bug that created side-effects in edge cases like when using the `RevitComparisonConfig.ParameterNumericTolerances` feature.

Revit_Engine: fix the copy of the DiffingConfig properties

---

Revit_Core_Engine/Convert/Lighting/FromRevit/Luminaire.cs
Revit_Core_Engine/Convert/Lighting/FromRevit/LuminaireType.cs
Revit_Core_Engine/Convert/Lighting/LightingFixture.cs
Revit_Core_Engine/Convert/Lighting/ToRevit/Luminaire.cs
Revit_Core_Engine/Convert/ToRevit.cs
Revit_Core_Engine/Query/BHoMType.cs
Revit_Core_Engine/Query/BuiltInCategories.cs
Revit_Core_Engine/Query/ElementType.cs
Revit_Core_Engine/Revit_Core_Engine.csproj
Revit_Engine/Query/GetRevitElementType.cs
Revit_Engine/Revit_Engine.csproj

https://github.com/BHoM/BHoM/pull/1501
Closes #1340
Closes #1347 
Added functionality for reading LightingFixtures as BHoM Luminaires. Includes reading position, Type Name, Revit Parameters/Identifiers and Orientation of LightingFixture. Note that for default LightingFixture families placed on a Ref Level, this orientation will be in the positive Z direction. While correct for representation of the Revit orientation, this may require additional handling to get desired orientation of the Luminaire for other usage. This may necessitate future additional methods for Revit vs Luminaire Orientation handling. 
Also added LightingFixture creation from Luminaires, with basic functionality for placing at specified location per LuminaireType Name and Model.
[Test …

Initial LightingFixture Convert Method and Read/Create Capability

---

Revit_Core_Engine/Convert/Revit/FromRevit/Parameter.cs
Revit_Core_Engine/Query/UnitTypePropertyName.cs

Closes #
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231350%2DAddSupportForPrimitiveCollections&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - only parameters that are measured in units should have `UnitType` property assigned (particularly relevant in lower versions of Revit, where it always was `UT_Number`).

Unit type of pulled parameters tweaked

---

Revit_Core_Engine/Create/FamilyInstance/FamilyInstance.cs

Closes #1352 
Fixed method for Placing One-Level Based Elements at a Point so it uses the Revit API Method that creates them hosted to the level, rather than the previous method which leaves them unhosted and therefore minimally manipulatable in Revit after creation.
[test files](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/%231353-Point%20Based%20Elem%20Level%20Hosting%20Fix?csf=1&web=1&e=4srCs6)
To test, open the rvt model and then follow the instructions in the script, first selecting Revit Elements and Pulling them, then Pushing them back to Revit and confirming they match the pulled elements. Use the plan view to confirm that pushed elements are still hosted to Level 1 (Not highlighted magenta). Use the 3d view to …

Updated Point Based One Level Placement to Place Per Level and Elevation

---

Revit_Core_Engine/Create/FamilyInstance/AdaptiveComponent.cs
Revit_Core_Engine/Create/FamilyInstance/FamilyInstance.cs

Closes #1365 
Added family symbol activate to avoid crashing if not activated.

`Create.FamilyInstance` - activate fix

---

Revit_Core_Engine/Query/Identifiers.cs

Closes #1369
Open the following models together with the .gh script located [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231370%2DWorksetBugOnPull&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4):
- _rac_basic_sample_project.rvt_ - workset should be empty (non-workshared model)
- _rme_advanced_sample_project.rvt_ - workset should be empty (non-workshared model)
- any workshared model - workset should be same as in Revit

Invalid workset information stopped from being passed on pull from non-workshared models

---

Revit_Core_Engine/Query/LocationCurve.cs
Revit_Core_Engine/Query/OrientationAngle.cs

Closes #1374 
Used `SortCollinear` and its principle to sort connectors of an MEP curve based on their origin point locations.
[SharePoint folder](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/%231375-HandleRandomConnectorsOrder?csf=1&web=1&e=4QgbKa)
- Use Revit 2020 or later
- Try pulling any cable tray by inputting its ID
- Check the output Json file after each pull to confirm every pull produces exactly the same result. In particular, check the start and end points of the element as well as its orientation angle.
Handle random order from `ConnectorManager.Connectors`

Handle random order from `ConnectorManager.Connectors`

---

Revit_Core_Engine/Query/PanelPlanes.cs

Closes part of #1287
Run the standard panel pull procedure and check the culprit highlighted in https://github.com/BHoM/Revit_Toolkit/issues/1287.

Warnings about nonplanar faces added when querying panel surfaces

---

Revit_Core_Engine/Query/HasVisibleParameter.cs

Method checking whether an element has a visible parameter

---

Revit_Core_Engine/Query/DrawingArea.cs

Closes #1388 
Added method returning drawing area outline from the title block family instance.

Add DrawingArea for FamilyInstance

---

Revit_Core_Engine/Objects/ActiveViewVisibilityContext.cs

Closes #1399 
Changed `linkInstance.Document` to `linkInstance.GetLinkDocument()`. This allows storing Ids of visible elements to the right document.
Please build this dependent PR and test on this Revit 2020 model called `Host.rvt` on [SharePoint](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/%231400-FixGetAllElementsVisibleInActiveView?csf=1&web=1&e=nf0scD).

Fixed GetAllElementsVisibleInActiveView

---

Revit_Core_Engine/Query/DrawingArea.cs

Closes #1401 
Fixed `Query.DrawingArea` to work correctly with various types of the title block and nested families.

Improve `Query.DrawingArea`

---

Revit_Core_Engine/Query/DrawingArea.cs

Closes #1403 
Added null check for empty symbol family types.

`Query.DrawingArea` - titleblock empty type bug fix

---

Revit_Core_Engine/Query/SpatialBoundCondition.cs
Revit_oM/Enums/BoundCondition.cs

Closes #1414 
- Renamed Redundant to Overlapping
- Added NoGeometry
- Added conditions for arriving at NoGeometry to the `SpatialBoundCondition` query method.
Please note the edge case for NoGeometry only exists in Revit models with volume computation turned on:
Building the repo should raise no error, and bot checks should pass.

Improve `SpatialBoundCondition` values

---

Revit_Core_Engine/Query/DoesIntersect.cs

Closes #1421
Add `DoesIntersect` method to check the intersection between point and element.

`DoesIntersect` - add intersection between point and element, point and solid, and solid vs solid

---

Revit_Core_Engine/Query/Bounds.cs
Revit_Core_Engine/Query/DoesIntersect.cs

Closes #
- Add `Bounds` for `IEnumerable<BoundingBoxXYZ>`
- Add transform input to `DoesIntersect`
Breaking change in DoesIntersect(BoundingBoxXYZ, Element) method - element transform calculation has been removed from the body as it can produce incorrect results. Transform of element has been added as an input.

`Query.Bounds` - add overload for collection of bounding boxes, `DoesIntesect` - add transform input

---

Revit_Core_Engine/Query/FaceTriangulationFactor.cs

Closes #1439
Sensitivity study and discussion available under #1439

Triangulation factor for Medium mesh quality changed from 0.5 to 0.3

---

.gitignore
Revit_Core_Engine/Convert/Geometry/FromRevit/Surface.cs

Closes #1462 
If externalLoop is null for any reason, we'll fall back on find the loop with the max area. This is slower than checking loop winding direction, but externalLoop is null in like 1 out of 1000 faces, so the performance hit isn't bad.
@pawelbaran : Do we need a test file for this PR?

Handle error when converting faces with open curve loops

---

Revit_Core_Adapter/CRUD/Read.cs
Revit_Core_Engine/Compute/SplitRequestTreeByLinks.cs
Revit_Core_Engine/Convert/FromRevit.cs
Revit_Core_Engine/Modify/Postprocess.cs

Closes #1477
This is quite a substantial change to the adapter mechanics, so thorough testing is required. Following tests to be done:

Issues with pulling from links fixed

---

Revit_Core_Engine/Query/ElementsInPath.cs

Closes #1487 
Replace `List<Element>` with `HashSet<int>` that fixes infinite loop bug and improves performance of the method. Added ordering by location point to get the results quicker.
[Revit 2022 - test model](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/%231488-ElementsInPathInfiniteLoopFix?csf=1&web=1&e=yCcYVO)

Elements In Path - infinite loop bug fix

---

Revit_Core_Engine/Query/ExternalCurveLoop.cs

Closes #1496
Extracted the external curve loop query to its own method
I simply cut & pasted the relevant code to a new file, so hopefully just code review will be enough!

Extract the external curve loop query to its own method

---

Revit_Core_Engine/Convert/Geometry/FromRevit/Surface.cs

Closes #1499 
Instead of comparing objects, we can detect internal openings by their bounding boxes, which should be always smaller than the main external boundary's bounding box.
TBC

Fix PlanarSurface conversion bug

---

Revit_Core_Engine/Query/SpecFromName.cs
Revit_Core_Engine/Query/UnitFromName.cs

Event suppression added to methods parsing properties of SpecTypeId and UnitTypeId

---

Revit_Core_Engine/Create/FamilyInstance/FamilyInstance.cs

Closes #
Fixed direction value for placing hosted elements on line elements (walls, ducts, pipes) if input orientation is null.

`FamilyInstance_WorkPlaneBased` - fixed direction for null orientation value

---

Revit_Core_Engine/Query/DoesIntersect.cs
Revit_Core_Engine/Query/IsContaining.cs

Closes #1530 
Not very beautiful, but temporary fix for `DoesIntersect` - point vs solid overload. Currently there are several overlapping methods in 3 different files (`DoesIntersect`, `IsContatining`, `IsInRange`) and they have to be unified in the future (issue #1465).

`DoesIntersect` point vs solid bug fix

---

Revit_Core_Engine/Convert/Architecture/FromRevit/Opening.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Beam.cs
Revit_Core_Engine/Convert/Physical/FromRevit/Column.cs
Revit_Core_Engine/Query/FramingElementProperty.cs

Closes #1519
See #1519.
Originally I expected the problem to occur to most types in Revit_Toolkit, but apparently columns and framing were almost the only pushable types that would suffer from it - so luckily the change is quite surgical and safe, as far as I can think of potential consequences.

Naming of pulled physical/arch elements unified

---

Revit_Core_Engine/Convert/Structure/FromRevit/Profile.cs

Closes #1548
UTs for pull column/framing profile - there is one difference compared to `develop`, a glulam built-up profile that was failing on `develop` and now comes out as a legit profile (see image below). Dedicated script to investigate uploaded to [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231549%2DEnableDisjointProfiles).
Besides that there should be no changes.

Support for disjoint profiles added

---

Revit_Core_Engine/Query/IsColourParameter.cs
Revit_Core_Engine/Query/ParameterValue.cs

Closes #1554
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231555%2DColourConvertBug) - pull the element, check if coloured preview works, then update and ideally pull again to confirm it all works. Worth testing against Revit 2021, 2022 and 2025 due to differences in the Revit API as well as .NET version.
Finally worth running unit tests for `Pull` as well.

Conversion of colour parameters fixed

---

Revit_Core_Engine/Query/ElementsInPath.cs
Revit_Core_Engine/Query/LocationPoint.cs
Revit_Core_Engine/Query/Space.cs

Closes #1559 
Added `Space` and `LocationPoint` methods that are very often used for MEP elements.

Add `Query.Space` and `Query.LocationPoint` methods

---

Revit_Core_Engine/Modify/SetType.cs

Closes #1586
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRevit%5FToolkit%2F%231587%2DFamilyUpdateBug)

Null reference bug on family update fixed
